/* ═══════════════════════════════════════════════════════════════════
   shop-names.js  —  商品名稱多語系對照表
   ═══════════════════════════════════════════════════════════════════

   ✅ 這是唯一需要編輯的翻譯檔案
      不需要動 shop.html 或任何其他檔案

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   新增翻譯：加一行即可
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   '商品中文名稱': { en: 'English', vi: '越南文', id: '印尼文', th: 'ภาษาไทย', zh: '中文' },

   ⚠  KEY 必須和 Firebase 裡的商品名稱一字不差（含空格、全半形）
   ⚠  en = 英文（菲律賓 PH），vi = 越南文，id = 印尼文 Club，th = 泰文，zh = 中文
      其他語系不需要填，系統自動顯示原文

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   修改後如何生效？
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   上傳本檔到伺服器後，同時將 shop-sw.js 裡的 APP_VERSION 加一位
   （如 v1.3.0 → v1.3.1），Service Worker 才會清除快取並拉取新版本。

   ═══════════════════════════════════════════════════════════════════ */

export const PRODUCT_NAME_MAP = {

  // ── 飲料 Drinks ──────────────────────────────────────────────────
  'ลิ้นจี่ใส่วุ้นมะพร้าว荔枝椰果': { en: 'Lychee with Coconut Jelly', vi: 'Vải thiều thạch dừa', id: 'Leci dengan Jeli Kelapa', th: 'ลิ้นจี่ใส่วุ้นมะพร้าว', zh: '荔枝椰果' },
  'สับปะรดใส่วุ้นมะพร้าว鳳梨椰果': { en: 'Pineapple with Coconut Jelly', vi: 'Dứa thạch dừa', id: 'Nanas dengan Jeli Kelapa', th: 'สับปะรดใส่วุ้นมะพร้าว', zh: '鳳梨椰果' },
  'DoubleC飲料': { en: 'Double C Drink', vi: 'Nước uống Double C', id: 'Minuman Double C', th: 'DoubleC飲料', zh: 'DoubleC飲料' },
  'DoubleC飲料1': { en: 'Double C Drink', vi: 'Nước uống Double C', id: 'Minuman Double C', th: 'DoubleC飲料', zh: 'DoubleC飲料' },
  'DoubleC飲料2': { en: 'Double C Drink', vi: 'Nước uống Double C', id: 'Minuman Double C', th: 'DoubleC飲料', zh: 'DoubleC飲料' },
  'M150': { en: 'M-150 Energy Drink', vi: 'Nước tăng lực M-150', id: 'Minuman Energi M-150', th: 'M150', zh: 'M150' },
  'Oishi飲料': { en: 'Oishi Drink', vi: 'Nước uống Oishi', id: 'Minuman Oishi', th: 'Oishi飲料', zh: 'Oishi飲料' },
  'Oishi飲料1': { en: 'Oishi Drink', vi: 'Nước uống Oishi', id: 'Minuman Oishi', th: 'Oishi飲料', zh: 'Oishi飲料' },
  'Oishi飲料2': { en: 'Oishi Drink', vi: 'Nước uống Oishi', id: 'Minuman Oishi', th: 'Oishi飲料', zh: 'Oishi飲料' },
  'Oishi飲料3': { en: 'Oishi Drink', vi: 'Nước uống Oishi', id: 'Minuman Oishi', th: 'Oishi飲料', zh: 'Oishi飲料' },
  'Oishi飲料4': { en: 'Oishi Drink', vi: 'Nước uống Oishi', id: 'Minuman Oishi', th: 'Oishi飲料', zh: 'Oishi飲料' },
  'กาโต๊ะ卡多果汁': { en: 'Kato Fruit Juice', vi: 'Nước trái cây Kato', id: 'Jus Buah Kato', th: 'กาโต๊ะ', zh: '卡多果汁' },
  'กาโต๊ะ卡多果汁1': { en: 'Kato Fruit Juice', vi: 'Nước trái cây Kato', id: 'Jus Buah Kato', th: 'กาโต๊ะ', zh: '卡多果汁' },
  'กาแฟกระป๋องไต้หวัน伯朗咖啡': { en: 'Brown Canned Coffee', vi: 'Cà phê lon Brown', id: 'Kopi Kaleng Brown', th: 'กาแฟกระป๋องไต้หวัน', zh: '伯朗咖啡' },
  'ชาไทย泰式奶茶': { en: 'Thai Milk Tea', vi: 'Trà sữa Thái', id: 'Teh Tarik Thailand / Thai Tea', th: 'ชาไทย', zh: '泰式奶茶' },
  'เครื่องดื่มรสมะขาม羅望子汁': { en: 'Tamarind Drink', vi: 'Nước me', id: 'Minuman Rasa Asam Jawa', th: 'เครื่องดื่มรสมะขาม', zh: '羅望子汁' },
  'โซดา金勇蘇打水': { en: 'King Yo Soda Water', vi: 'Nước Soda King Yo', id: 'Air Soda King Yo', th: 'โซดา', zh: '金勇蘇打水' },
  'โซดาช้าง大象蘇打水': { en: 'Chang Soda Water', vi: 'Nước Soda Chang', id: 'Air Soda Chang', th: 'โซดาช้าง', zh: '大象蘇打水' },
  'โซดาสิงห์勝獅蘇打水': { en: 'Singha Soda Water', vi: 'Nước Soda Singha', id: 'Air Soda Singha', th: 'โซดาสิงห์', zh: '勝獅蘇打水' },
  'นมถั่วเหลืองV豆奶1': { en: 'Vitamilk Soy Milk', vi: 'Sữa đậu nành Vitamilk', id: 'Susu Kacang Kedelai Vitamilk', th: 'นมถั่วเหลือง Vitamilk', zh: 'V豆奶' },
  'นมถั่วเหลืองV豆奶5': { en: 'Vitamilk Soy Milk', vi: 'Sữa đậu nành Vitamilk', id: 'Susu Kacang Kedelai Vitamilk', th: 'นมถั่วเหลือง Vitamilk', zh: 'V豆奶' },
  'นมถั่วเหลืองV豆奶3': { en: 'Vitamilk Soy Milk', vi: 'Sữa đậu nành Vitamilk', id: 'Susu Kacang Kedelai Vitamilk', th: 'นมถั่วเหลือง Vitamilk', zh: 'V豆奶' },
  'นมถั่วเหลืองV豆奶': { en: 'Vitamilk Soy Milk', vi: 'Sữa đậu nành Vitamilk', id: 'Susu Kacang Kedelai Vitamilk', th: 'นมถั่วเหลือง Vitamilk', zh: 'V豆奶' },
  'นมถั่วเหลืองV豆奶2': { en: 'Vitamilk Soy Milk', vi: 'Sữa đậu nành Vitamilk', id: 'Susu Kacang Kedelai Vitamilk', th: 'นมถั่วเหลือง Vitamilk', zh: 'V豆奶' },
  'นมถั่วเหลืองV豆奶4': { en: 'Vitamilk Soy Milk', vi: 'Sữa đậu nành Vitamilk', id: 'Susu Kacang Kedelai Vitamilk', th: 'นมถั่วเหลือง Vitamilk', zh: 'V豆奶' },
  'นมถั่วเหลืองแลคตาซอย力大獅豆奶': { en: 'Lactasoy Soy Milk', vi: 'Sữa đậu nành Lactasoy', id: 'Susu Kacang Kedelai Lactasoy', th: 'นมถั่วเหลืองแลคตาซอย', zh: '力大獅豆奶' },
  'นมเปรี้ยวดัชมิลล์酸奶2': { en: 'Dutch Mill Drinking Yogurt', vi: 'Sữa chua uống Dutch Mill', id: 'Yoghurt Cetak', th: 'นมเปรี้ยวดัชมิลล์', zh: '酸奶' },
  'นมเปรี้ยวดัชมิลล์酸奶1': { en: 'Dutch Mill Drinking Yogurt', vi: 'Sữa chua uống Dutch Mill', id: 'Yoghurt Cetak', th: 'นมเปรี้ยวดัชมิลล์', zh: '酸奶' },
  'นมเปรี้ยวดัชมิลล์酸奶': { en: 'Dutch Mill Drinking Yogurt', vi: 'Sữa chua uống Dutch Mill', id: 'Yoghurt Cetak', th: 'นมเปรี้ยวดัชมิลล์', zh: '酸奶' },
  'เบอดี้birdyCofe易開罐': { en: 'Birdy Canned Coffee', vi: 'Cà phê lon Birdy', id: 'Kopi Kaleng Birdy', th: 'เบอดี้ birdy', zh: 'birdyCofe易開罐' },
  'เบอดี้Nescafé 易開罐': { en: 'Nescafe Canned Coffee', vi: 'Cà phê lon Nescafe', id: 'Kopi Kaleng Nescafe', th: 'เบอดี้ Nescafé', zh: 'Nescafé 易開罐' },
  'น้ำเปล่า礦泉水': { en: 'Mineral Water', vi: 'Nước khoáng', id: 'Air Mineral', th: 'น้ำเปล่า', zh: '礦泉水' },
  'น้ำตาลสด椰香花蜜': { en: 'Fresh Coconut Flower Nectar', vi: 'Nước mật hoa dừa tươi', id: 'Nira Kelapa Segar', th: 'น้ำตาลสด', zh: '椰香花蜜' },
  'น้ำมะพร้าว椰子汁': { en: 'Coconut Juice', vi: 'Nước dừa', id: 'Air Kelapa', th: 'น้ำมะพร้าว', zh: '椰子汁' },
  'สปอนเซอร์運動飲料沙賓': { en: 'Sponsor Electrolyte Beverage', vi: 'Nước uống thể thao Sponsor', id: 'Minuman Isotonik Sponsor', th: 'สปอนเซอร์', zh: '運動飲料沙賓' },
  'อีฟน้ำเก๊กฮวย菊花茶': { en: 'If Chrysanthemum Tea', vi: 'Trà hoa cúc If', id: 'Teh Krisan If', th: 'อีฟน้ำเก๊กฮวย', zh: '菊花茶' },
  'M150-10ขวด罐': { en: 'M-150 Energy Drink (10 Bottles)', vi: 'Nước tăng lực M-150 (Lốc 10 chai)', id: 'Minuman Energi M-150 (10 Botol)', th: 'เอ็ม-150 10 ขวด', zh: 'M150-10ขวด罐' },
  'เอ็ม150ยกลังM150箱': { en: 'M-150 Energy Drink (Case)', vi: 'Thùng nước tăng lực M-150', id: 'Minuman Energi M-150 (Karton)', th: 'เอ็ม-150 ยกลัง', zh: 'M150箱' },
  'โคคาโคล่า可口可樂330ml': { en: 'Coca-Cola330ml', vi: 'Coca-Cola330ml', id: 'Coca-Cola330ml', th: 'โคคาโคล่า330ml', zh: '可口可樂330ml' },
  'โคคาโคล่า可口可樂2L': { en: 'Coca-Cola2L', vi: 'Coca-Cola2L', id: 'Coca-Cola2L', th: 'โคคาโคล่า2L', zh: '可口可樂2L' },






  // ── 食品 Food ────────────────────────────────────────────────────
  '美露': { en: 'Milo', vi: 'Sữa Milo', id: 'Milo', th: 'Milo', zh: '美露' },
  'Birdy-red': { en: 'Birdy Cafe', vi: 'Cà phê Birdy', id: 'Kopi Birdy Cafe', th: 'BirdyCafe', zh: 'BirdyCafe' },
  'BirdyCafe': { en: 'Birdy Cafe', vi: 'Cà phê Birdy', id: 'Kopi Birdy Cafe', th: 'BirdyCafe', zh: 'BirdyCafe' },
  'CappuCafe': { en: 'Cappuccino Coffee', vi: 'Cà phê Cappuccino', id: 'Kopi Cappuccino', th: 'CappuCafe', zh: 'CappuCafe' },
  'Nescafe-green': { en: 'Nescafe Green', vi: 'Nescafe xanh lá', id: 'Nescafe Hijau', th: 'Nescafe-green', zh: 'Nescafe-green' },
  'Nescafe-red': { en: 'Nescafe Red', vi: 'Nescafe đỏ', id: 'Nescafe Merah', th: 'Nescafe-red', zh: 'Nescafe-red' },
  'เนสกาแฟกระปุกNeecafe罐': { en: 'Nescafe Coffee Jar', vi: 'Cà phê hòa tan hũ Nescafe', id: 'Kopi Bubuk Toples Nescafe', th: 'เนสกาแฟกระปุก', zh: 'Neecafe罐' },
  'มะขามเปียก羅望子': { en: 'Dried Tamarind Block', vi: 'Me chua chín đóng vắt', id: 'Asam Jawa Kering', th: 'มะขามเปียก', zh: '羅望子' },
  'มะม่วงแช่อิ่ม醃芒果1': { en: 'Pickled Sweet Mango', vi: 'Xoài ngâm chua ngọt', id: 'Manisan Mangga', th: 'มะม่วงแช่อิ่ม', zh: '醃芒果' },
  'มะม่วงแช่อิ่ม醃芒果': { en: 'Pickled Sweet Mango', vi: 'Xoài ngâm chua ngọt', id: 'Manisan Mangga', th: 'มะม่วงแช่อิ่ม', zh: '醃芒果' },
  'ม็อคโคน่า摩可納Cafe-green': { en: 'Moccona Instant Coffee', vi: 'Cà phê hòa tan Moccona', id: 'Kopi Instan Moccona', th: 'ม็อคโคน่า เขียว', zh: '摩可納Cafe' },
  'ม็อคโคน่า摩可納Cafe-red': { en: 'Moccona Instant Coffee', vi: 'Cà phê hòa tan Moccona', id: 'Kopi Instan Moccona', th: 'ม็อคโคน่า แดง', zh: '摩可納Cafe' },
  'มาม่าMama泡麵': { en: 'Mama Instant Noodles Assorted', vi: 'Thùng mì Mama lộn xộn vị', id: 'Mi Instan Mama Aneka Rasa', th: 'มาม่าคละรส', zh: '不指定口味泡麵' },
  'มาม่าMama泡麵碗': { en: 'Mama Instant Noodles', vi: 'Mì tô ăn liền Mama', id: 'Mie Instan Wadah Mangkok Mama', th: 'มาม่าถ้วย', zh: 'Mama泡麵碗' },
  'แคบหมู豬皮酥': { en: 'Pork Cracklings / Pork Rinds', vi: 'Da heo chiên giòn', id: 'Kerupuk Kulit Babi', th: 'แคบหมู', zh: '豬皮酥' },
  'ปลาเส้นปรุงรส鱈魚香絲': { en: 'Taro Seasoned Fish Snack', vi: 'Snack cá sợi tẩm vị', id: 'Camilan Stik Ikan Berbumbu', th: 'ปลาเส้นปรุงรส', zh: '鱈魚香絲' },
  'ปลาเส้นปรุงรส鱈魚香絲1': { en: 'Taro Seasoned Fish Snack', vi: 'Snack cá sợi tẩm vị', id: 'Camilan Stik Ikan Berbumbu', th: 'ปลาเส้นปรุงรส', zh: '鱈魚香絲' },
  'ปลาเส้นปรุงรส鱈魚香絲3': { en: 'Taro Seasoned Fish Snack', vi: 'Snack cá sợi tẩm vị', id: 'Camilan Stik Ikan Berbumbu', th: 'ปลาเส้นปรุงรส', zh: '鱈魚香絲' },
  'ปลาเส้นปรุงรส鱈魚香絲2': { en: 'Taro Seasoned Fish Snack', vi: 'Snack cá sợi tẩm vị', id: 'Camilan Stik Ikan Berbumbu', th: 'ปลาเส้นปรุงรส', zh: '鱈魚香絲' },
  'กล้วยอบน้ำผึ้ง香蕉蜜片': { en: 'Honey Baked Bananas', vi: 'Chuối nướng mật ong', id: 'Pisang Panggang Madu', th: 'กล้วยอบน้ำผึ้ง', zh: '香蕉蜜片' },
  'โกแก่大豆哥': { en: 'Koh-Kae Peanut Snacks', vi: 'Đậu phộng Koh-Kae', id: 'Kacang Koh-Kae', th: 'โกแก่', zh: '大豆哥' },
  'โกแก่大豆哥1': { en: 'Koh-Kae Peanut Snacks', vi: 'Đậu phộng Koh-Kae', id: 'Kacang Koh-Kae', th: 'โกแก่', zh: '大豆哥' },
  'โกแก่大豆哥2': { en: 'Koh-Kae Peanut Snacks', vi: 'Đậu phộng Koh-Kae', id: 'Kacang Koh-Kae', th: 'โกแก่', zh: '大豆哥' },
  'โกแก่大豆哥3': { en: 'Koh-Kae Peanut Snacks', vi: 'Đậu phộng Koh-Kae', id: 'Kacang Koh-Kae', th: 'โกแก่', zh: '大豆哥' },
  'โกแก่大豆哥4': { en: 'Koh-Kae Peanut Snacks', vi: 'Đậu phộng Koh-Kae', id: 'Kacang Koh-Kae', th: 'โกแก่', zh: '大豆哥' },
  'โกแก่大豆哥5': { en: 'Koh-Kae Peanut Snacks', vi: 'Đậu phộng Koh-Kae', id: 'Kacang Koh-Kae', th: 'โกแก่', zh: '大豆哥' },
  'ขนม大王餅乾': { en: 'Dawang Biscuits', vi: 'Bánh quy Dawang', id: 'Biskuit Dawang', th: 'ขนม', zh: '大王餅乾' },
  'ขนม大王餅乾1': { en: 'Dawang Biscuits', vi: 'Bánh quy Dawang', id: 'Biskuit Dawang', th: 'ขนม', zh: '大王餅乾' },
  'ขนม大王餅乾2': { en: 'Dawang Biscuits', vi: 'Bánh quy Dawang', id: 'Biskuit Dawang', th: 'ขนม', zh: '大王餅乾' },
  'ขนม牛角餅乾': { en: 'Horn Crackers', vi: 'Bánh sừng bò', id: 'Keripik Tanduk', th: 'ขนม', zh: '牛角餅乾' },
  'ขนม牛角餅乾1': { en: 'Horn Crackers', vi: 'Bánh sừng bò', id: 'Keripik Tanduk', th: 'ขนม', zh: '牛角餅乾' },
  'ขนม牛角餅乾2': { en: 'Horn Crackers', vi: 'Bánh sừng bò', id: 'Keripik Tanduk', th: 'ขนม', zh: '牛角餅乾' },
  'ขนม牛角餅乾3': { en: 'Horn Crackers', vi: 'Bánh sừng bò', id: 'Keripik Tanduk', th: 'ขนม', zh: '牛角餅乾' },
  'ขนม牛角餅乾4': { en: 'Horn Crackers', vi: 'Bánh sừng bò', id: 'Keripik Tanduk', th: 'ขนม', zh: '牛角餅乾' },
  'ขนม玉米餅乾': { en: 'Corn Crackers', vi: 'Bánh quy ngô', id: 'Keripik Jagung', th: 'ขนม', zh: '玉米餅乾' },
  'ขนม玉米餅乾1': { en: 'Corn Crackers', vi: 'Bánh quy ngô', id: 'Keripik Jagung', th: 'ขนม', zh: '玉米餅乾' },
  'ขนม玉米餅乾2': { en: 'Corn Crackers', vi: 'Bánh quy ngô', id: 'Keripik Jagung', th: 'ขนม', zh: '玉米餅乾' },
  'ขนม地瓜餅乾': { en: 'Sweet Potato Crackers', vi: 'Bánh quy khoai lang', id: 'Keripik Ubi', th: 'ขนม', zh: '地瓜餅乾' },
  'ขนม青椒餅乾': { en: 'Green Pepper Crackers', vi: 'Bánh quy ớt chuông xanh', id: 'Keripik Paprika Hijau', th: 'ขนม', zh: '青椒餅乾' },
  'ขนม馬鈴薯餅乾': { en: 'Potato Crackers', vi: 'Bánh quy khoai tây', id: 'Keripik Kentang', th: 'ขนม', zh: '馬鈴薯餅乾' },
  'ขนม馬鈴薯餅乾1': { en: 'Potato Crackers', vi: 'Bánh quy khoai tây', id: 'Keripik Kentang', th: 'ขนม', zh: '馬鈴薯餅乾' },
  'ขนม番茄餅乾': { en: 'Tomato Crackers', vi: 'Bánh quy cà chua', id: 'Keripik Tomat', th: 'ขนม', zh: '番茄餅乾' },
  'ขนม樂事薯片': { en: 'Lay\'s Potato Chips', vi: 'Khoai tây chiên Lay\'s', id: 'Keripik Kentang Lay\'s', th: 'ขนม', zh: '樂事薯片' },
  'ขนม蝦味先': { en: 'Shrimp Crackers', vi: 'Bánh phồng tôm Siaw-Wei-Sien', id: 'Kerupuk Udang', th: 'ขนม', zh: '蝦味先' },
  'ขนมขาไก่Mix香脆麵條': { en: 'Mix Crispy Noodle Snack', vi: 'Snack mì giòn Mix', id: 'Camilan Mie Krispi Mix', th: 'ขนมขาไก่Mix', zh: '香脆麵條' },
  'ขนมขาไก่Mix香脆麵條1': { en: 'Mix Crispy Noodle Snack', vi: 'Snack mì giòn Mix', id: 'Camilan Mie Krispi Mix', th: 'ขนมขาไก่Mix', zh: '香脆麵條' },
  'ขนมขาไก่Mix香脆麵條2': { en: 'Mix Crispy Noodle Snack', vi: 'Snack mì giòn Mix', id: 'Camilan Mie Krispi Mix', th: 'ขนมขาไก่Mix', zh: '香脆麵條' },
  'ขนมขาไก่Mix香脆麵條3': { en: 'Mix Crispy Noodle Snack', vi: 'Snack mì giòn Mix', id: 'Camilan Mie Krispi Mix', th: 'ขนมขาไก่Mix', zh: '香脆麵條' },
  'ขนมปลาหวาน風味甜魚片': { en: 'Sweet Fish Snack', vi: 'Snack cá ngọt', id: 'Camilan Ikan Manis', th: 'ขนมปลาหวาน', zh: '風味甜魚片' },
  'ขนมเอลเช่24ชิ้นEllse蛋糕': { en: 'Ellse Cake 24 Pack', vi: 'Hộp 24 bánh Ellse', id: 'Kue Ellse Isi 24', th: 'ขนมเอลเช่24ชิ้น', zh: 'Ellse蛋糕24個' },
  'ขนมเอลเช่24ชิ้นEllse蛋糕1': { en: 'Ellse Cake 24 Pack', vi: 'Hộp 24 bánh Ellse', id: 'Kue Ellse Isi 24', th: 'ขนมเอลเช่24ชิ้น', zh: 'Ellse蛋糕24個' },
  'ขนมเอลเช่24ชิ้นEllse蛋糕2': { en: 'Ellse Cake 24 Pack', vi: 'Hộp 24 bánh Ellse', id: 'Kue Ellse Isi 24', th: 'ขนมเอลเช่24ชิ้น', zh: 'Ellse蛋糕24個' },
  'ขนมเอลเช่24ชิ้นEllse蛋糕3': { en: 'Ellse Cake 24 Pack', vi: 'Hộp 24 bánh Ellse', id: 'Kue Ellse Isi 24', th: 'ขนมเอลเช่24ชิ้น', zh: 'Ellse蛋糕24個' },
  'ขนมเอลเช่24ชิ้นEllse蛋糕4': { en: 'Ellse Cake 24 Pack', vi: 'Hộp 24 bánh Ellse', id: 'Kue Ellse Isi 24', th: 'ขนมเอลเช่24ชิ้น', zh: 'Ellse蛋糕24個' },
  'ขนมเอลเช่24ชิ้นEllse蛋糕5': { en: 'Ellse Cake 24 Pack', vi: 'Hộp 24 bánh Ellse', id: 'Kue Ellse Isi 24', th: 'ขนมเอลเช่24ชิ้น', zh: 'Ellse蛋糕24個' },
  'ขนมเอลเช่24ชิ้นEllse蛋糕6': { en: 'Ellse Cake 24 Pack', vi: 'Hộp 24 bánh Ellse', id: 'Kue Ellse Isi 24', th: 'ขนมเอลเช่24ชิ้น', zh: 'Ellse蛋糕24個' },
  'เม็ดมะม่วงหิมพานต์堅果': { en: 'Cashew Nuts', vi: 'Hạt điều', id: 'Kacang Mete', th: 'เม็ดมะม่วงหิมพานต์', zh: '堅果' },
  'ลูกอมฮอลล์LEMONSODA': { en: 'Halls Candy Lemon Soda', vi: 'Kẹo Halls Lemon Soda', id: 'Permen Halls Lemon Soda', th: 'ลูกอมฮอลล์ เลมอนโซดา', zh: 'LEMONSODA' },
  'ลูกอมฮอลล์Mentholyptus': { en: 'Halls Candy Mentholyptus', vi: 'Kẹo Halls Mentholyptus', id: 'Permen Halls Mentholyptus', th: 'ลูกอมฮอลล์ เมนโทลิปตัส', zh: 'Mentholyptus' },
  'โอวัลติน阿華田': { en: 'Ovaltine', vi: 'Ovaltine', id: 'Ovaltine', th: 'โอวัลติน', zh: '阿華田' },
  'กล้วยฉาบ香蕉脆片': { en: 'Sweet Banana Chips', vi: 'Chuối sấy giòn', id: 'Keripik Pisang', th: 'กล้วยฉาบ', zh: '香蕉脆片' },
  'แคบไก่雞皮酥': { en: 'Crispy Chicken Skin', vi: 'Da gà chiên giòn', id: 'Kulit Ayam Krispi', th: 'แคบไก่', zh: '雞皮酥' },
  'แคบหมูรสเผ็ด豬皮酥辣味': { en: 'Spicy Crispy Pork Rinds', vi: 'Da heo chiên giòn vị cay', id: 'Kerupuk Kulit Babi Pedas', th: 'แคบหมูรสเผ็ด', zh: '豬皮酥辣味' },
  'ตำไทย原味涼拌青木瓜': { en: 'Thai Green Papaya Salad (Tam Thai)', vi: 'Gỏi đu đủ Som Tum Thái', id: 'Salad Pepaya Muda (Som Tum Thai)', th: 'ตำไทย', zh: '原味涼拌青木瓜' },
  'ส้มตำปูปลาร้า螃蟹涼拌青木瓜': { en: 'Green Papaya Salad with Crab and Fermented Fish (Tam Pu Pla Ra)', vi: 'Gỏi đu đủ ba khía mắm cá', id: 'Salad Pepaya Muda dengan Kepiting dan Pasta Ikan Fermentasi', th: 'ส้มตำปูปลาร้า', zh: '螃蟹涼拌青木瓜' },
  'มาม่ายกลัง泡麵箱': { en: 'Mama Instant Noodles Assorted (Case)', vi: 'Thùng mì Mama lộn xộn vị', id: 'Mi Instan Mama Aneka Rasa (Karton)', th: 'มาม่ายกลังคละรส', zh: '不指定口味泡麵箱' },
  'ข้าวเหนียว糯米飯': { en: 'Cooked Sticky Rice', vi: 'Xôi', id: 'Nasi Ketan Matang', th: 'ข้าวเหนียว', zh: '糯米飯' },
  


  // ── 調味品 Seasonings ─────────────────────────────────────────────
  'น้ำตาล二號砂糖': { en: 'Brown Sugar', vi: 'Đường nâu', id: 'Gula Merah', th: 'น้ำตาล', zh: '二號砂糖' },
  'น้ำมันถั่วเหลือง大豆沙拉油': { en: 'Soybean Salad Oil', vi: 'Dầu đậu nành', id: 'Minyak Kedelai', th: 'น้ำมันถั่วเหลือง', zh: '大豆沙拉油' },
  'ซีอิ๊วหวานABC調味液': { en: 'ABC Sweet Soy Sauce', vi: 'Nước tương ngọt ABC', id: 'Kecap Manis ABC', th: 'ซีอิ๊วหวาน', zh: 'ABC調味液' },
  'กระเทียมดอง醃蒜頭': { en: 'Pickled Garlic', vi: 'Tỏi ngâm', id: 'Bawang Putih Acar', th: 'กระเทียมดอง', zh: '醃蒜頭' },
  'ก๋วยเตี๋ยวเย็นตาโฟ火鍋料': { en: 'Yentafo Noodles Hot Pot Ingredients', vi: 'Nguyên liệu lẩu Yentafo', id: 'Bahan Hot Pot Mie Yentafo', th: 'ก๋วยเตี๋ยวเย็นตาโฟ', zh: '火鍋料' },
  'กะปิ蝦膏金勇180g': { en: 'Shrimp Paste Kim Yong 180g', vi: 'Mắm tôm Kim Yong 180g', id: 'Terasi Kim Yong 180g', th: 'กะปิ', zh: '蝦膏金勇180g' },
  'กะปิ蝦膏金勇400g': { en: 'Shrimp Paste Kim Yong 400g', vi: 'Mắm tôm Kim Yong 400g', id: 'Terasi Kim Yong 400g', th: 'กะปิ', zh: '蝦膏金勇400g' },
  'เกลือ碘鹽': { en: 'Iodized Salt', vi: 'Muối i-ốt', id: 'Garam Beryodium', th: 'เกลือ', zh: '碘鹽' },
  'ขนุนกระป๋อง波羅密罐頭': { en: 'Canned Jackfruit', vi: 'Mít đóng hộp', id: 'Nangka Kalengan', th: 'ขนุนกระป๋อง', zh: '波羅密罐頭' },
  'คนเนชั่น三花調製奶水': { en: 'Carnation Evaporated Milk', vi: 'Sữa đặc Carnation', id: 'Susu Evaporasi Carnation', th: 'คนเนชั่น', zh: '三花調製奶水' },
  'คนอไก่雞湯塊': { en: 'Knorr Chicken Bouillon Cube', vi: 'Hạt nêm Knorr vị gà', id: 'Kaldu Blok Ayam Knorr', th: 'คนอไก่', zh: '雞湯塊' },
  'คนอต้มยำ酸辣湯塊': { en: 'Knorr Tom Yum Bouillon Cube', vi: 'Hạt nêm Knorr vị Tom Yum', id: 'Kaldu Blok Tom Yum Knorr', th: 'คนอต้มยำ', zh: '酸辣湯塊' },
  'คนหมู豬湯塊': { en: 'Knorr Pork Bouillon Cube', vi: 'Hạt nêm Knorr vị heo', id: 'Kaldu Blok Babi Knorr', th: 'คนหมู', zh: '豬湯塊' },
  'ซอยฝาเขียวใหญ่金山牌醬油1000': { en: 'Golden Mountain Green Cap Seasoning Sauce 1000ml', vi: 'Nước tương nắp xanh Golden Mountain 1000ml', id: 'Saus Penyedap Golden Mountain Tutup Hijau 1000ml', th: 'ซอยฝาเขียวใหญ่', zh: '金山牌醬油1000' },
  'ซอยฝาเขียวใหญ่金山牌醬油200': { en: 'Golden Mountain Green Cap Seasoning Sauce 200ml', vi: 'Nước tương nắp xanh Golden Mountain 200ml', id: 'Saus Penyedap Golden Mountain Tutup Hijau 200ml', th: 'ซอยฝาเขียวใหญ่', zh: '金山牌醬油200' },
  'ซอยฝาเขียวใหญ่金山牌醬油600': { en: 'Golden Mountain Green Cap Seasoning Sauce 600ml', vi: 'Nước tương nắp xanh Golden Mountain 600ml', id: 'Saus Penyedap Golden Mountain Tutup Hijau 600ml', th: 'ซอยฝาเขียวใหญ่', zh: '金山牌醬油600' },
  'ซอสผัดผงกะหรี่泰式螃蟹料理包': { en: 'Thai Stir-Fried Crab Curry Sauce Pack', vi: 'Gói sốt xào bột cà ri cua kiểu Thái', id: 'Saus Bumbu Tumis Kepiting Kari Thailand', th: 'ซอสผัดผงกะหรี่', zh: '泰式螃蟹料理包' },
  'ซอสพริก上等辣椒醬': { en: 'Premium Chili Sauce', vi: 'Tương ớt thượng hạng', id: 'Saus Cabai Premium', th: 'ซอสพริก', zh: '上等辣椒醬' },
  'ซอสหอยเส็ก主婦蠔油4500': { en: 'Maekrua Oyster Sauce 4500ml', vi: 'Dầu hào Maekrua 4500ml', id: 'Saus Tiram Maekrua 4500ml', th: 'ซอสหอยเส็ก', zh: '主婦蠔油4500' },
  'ซอสหอยเส็ก蠔油150': { en: 'Oyster Sauce 150ml', vi: 'Dầu hào 150ml', id: 'Saus Tiram 150ml', th: 'ซอสหอยเส็ก', zh: '主婦蠔油150' },
  'ซอสหอยเส็ก蠔油300': { en: 'Oyster Sauce 300ml', vi: 'Dầu hào 300ml', id: 'Saus Tiram 300ml', th: 'ซอสหอยเส็ก', zh: '主婦蠔油300' },
  'ซอสหอยเส็ก蠔油600': { en: 'Oyster Sauce 600ml', vi: 'Dầu hào 600ml', id: 'Saus Tiram 600ml', th: 'ซอสหอยเส็ก', zh: '主婦蠔油600' },
  'ฉู่ฉี่สามแม่ครัว椰漿沙丁魚': { en: 'Three Chefs Sardines in Chu Chee Curry', vi: 'Cá mòi sốt cà ri nước cốt dừa Three Chefs', id: 'Tiga Koki Sarden Saus Kari Santan', th: 'ฉู่ฉี่สามแม่ครัว', zh: '椰漿沙丁魚' },
  'งาขาว炸粉': { en: 'Fried Flour with White Sesame', vi: 'Bột chiên mè trắng', id: 'Tepung Goreng Wijen Putih', th: 'งาขาว', zh: '炸粉' },
  'เงาะในน้ำเชื่อม紅毛丹罐頭': { en: 'Rambutan in Syrup Canned', vi: 'Chôm chôm ngâm đường đóng hộp', id: 'Manisan Rambutan Kaleng', th: 'เงาะในน้ำเชื่อม', zh: '紅毛丹罐頭' },
  'เงาะสับปะรดกระป๋อง波蘿紅毛丹罐頭': { en: 'Rambutan stuffed with Pineapple in Syrup Canned', vi: 'Chôm chôm nhân dứa đóng hộp', id: 'Rambutan Isi Nanas Kaleng', th: 'เงาะสับปะรดกระป๋อง', zh: '波蘿紅毛丹罐頭' },
  'เครื่องผโล้滷包': { en: 'Chinese Five Spice Stew Spices Pack', vi: 'Gói gia vị hầm phá lấu (ngũ vị hương)', id: 'Bumbu Kuah Semur / Ngo Hiong', th: 'เครื่องผโล้', zh: '滷包' },
  'ผงชูรส味素250': { en: 'Ajinomoto MSG 250g', vi: 'Bột ngọt 250g', id: 'Micin 250g', th: 'ผงชูรส 250g', zh: '味素250' },
  'ผงชูรส味素500': { en: 'Ajinomoto MSG 500g', vi: 'Bột ngọt 500g', id: 'Micin 500g', th: 'ผงชูรส 500g', zh: '味素500' },
  'ผงชูรส味素800': { en: 'Ajinomoto MSG 800g', vi: 'Bột ngọt 800g', id: 'Micin 800g', th: 'ผงชูรส 800g', zh: '味素800' },
  'ผงชูรส味素85': { en: 'Ajinomoto MSG 85g', vi: 'Bột ngọt 85g', id: 'Micin 85g', th: 'ผงชูรส 85g', zh: '味素85' },
  'ผงต้มยำ酸辣調味粉': { en: 'Tom Yum Seasoning Powder', vi: 'Bột gia vị lẩu chua cay Tom Yum', id: 'Bumbu Bubuk Tom Yum', th: 'ผงต้มยำ', zh: '酸辣調味粉' },
  'ผงปรุงรสก๋วยเตี๋ยว牛肉湯粉GOSTO': { en: 'Gosto Noodle Soup Seasoning Powder', vi: 'Bột gia vị nấu nước dùng hủ tiếu', id: 'Bumbu Bubuk Kuah Sup Mie Rasa Sapi Gosto', th: 'ผงปรุงรสก๋วยเตี๋ยวเนื้อ Gosto', zh: '牛肉湯粉GOSTO' },
  'ผงปรุงรสก๋วยเตี๋ยวน้ำข้นฟ้าไทย粿條調味粉': { en: 'Fa Thai Thick Soup Noodle Seasoning Powder', vi: 'Bột gia vị súp hủ tiếu nước lèo đặc Fa Thai', id: 'Bumbu Bubuk Kuah Mie Kuah Kental Fa Thai', th: 'ผงปรุงรสก๋วยเตี๋ยวน้ำข้น ฟ้าไทย', zh: '粿條調味粉' },
  'ผงปรุงรสก๋วยเตี๋ยวน้ำใส粿條調味粉': { en: 'Fa Thai Clear Soup Noodle Seasoning Powder', vi: 'Bột gia vị súp hủ tiếu nước lèo trong Fa Thai', id: 'Bumbu Bubuk Kuah Mie Kuah Bening Fa Thai', th: 'ผงปรุงรสก๋วยเตี๋ยวน้ำใส ฟ้าไทย', zh: '粿條調味粉' },
  'ผงฟู蛋糕粉': { en: 'Baking Powder', vi: 'Bột nở', id: 'Baking Powder', th: 'ผงฟู', zh: '蛋糕粉' },
  'ผงวุ้น燕菜粉': { en: 'Agar-Agar Powder', vi: 'Bột rau câu', id: 'Tepung Agar-Agar', th: 'ผงวุ้น', zh: '燕菜粉' },
  'ผงหมักหมู醃烤調味粉': { en: 'Pork Marinade Seasoning Powder', vi: 'Bột gia vị ướp thịt lợn (thịt heo)', id: 'Bumbu Bubuk Rendaman Daging Babi', th: 'ผงหมักหมู', zh: '醃烤調味粉' },
  'ผักกาดดอง華南菜': { en: 'Pickled Mustard Greens', vi: 'Dưa cải muối chua hiệu Hoa Nam', id: 'Sawi Asin', th: 'ผักกาดดอง ฮั่วหนำ', zh: '華南菜' },
  'พริกแกงเขียวหวาน有心綠咖哩醬500g': { en: 'Cock Brand Green Curry Paste 500g', vi: 'Sốt cà ri xanh hiệu Con Gà (Cock Brand) 500g', id: 'Pasta Kari Hijau Cap Ayam (Cock Brand) 500g', th: 'พริกแกงเขียวหวาน 500g', zh: '有心綠咖哩醬500g' },
  'พริกแกงเขียวหวาน有心綠咖哩醬100g': { en: 'Cock Brand Green Curry Paste 100g', vi: 'Sốt cà ri xanh hiệu Con Gà (Cock Brand) 100g', id: 'Pasta Kari Hijau Cap Ayam (Cock Brand) 100g', th: 'พริกแกงเขียวหวาน 100g', zh: '有心綠咖哩醬100g' },
  'พริกแกงไตปลา料理包': { en: 'Southern Thai Fish Organs Sour Curry Paste (Tai Pla) Meal Kit', vi: 'Gói gia vị nấu cà ri lòng cá kiểu miền Nam (Tai Pla)', id: 'Paket Bumbu Kari Perut Ikan Khas Thailand Selatan (Tai Pla)', th: 'พริกแกงไตปลา', zh: '料理包' },
  'พริกแกงน้ำยา有心咖哩醬100g': { en: 'Cock Brand Kanom Jeen Noodle Curry Paste 100g', vi: 'Sốt cà ri ăn bún (Nam Ya) hiệu Con Gà 100g', id: 'Pasta Kari Kuah Bihun (Nam Ya) Cap Ayam 100g', th: 'พริกแกงน้ำยา 100g', zh: '有心咖哩醬100g' },
  'พริกแกงเผ็ด有心紅咖哩500g': { en: 'Cock Brand Red Curry Paste 500g', vi: 'Sốt cà ri đỏ hiệu Con Gà (Cock Brand) 500g', id: 'Pasta Kari Merah Cap Ayam (Cock Brand) 500g', th: 'พริกแกงเผ็ด 500g', zh: '有心紅咖哩500g' },
  'พริกแกงเผ็ด有心紅咖哩100g': { en: 'Cock Brand Red Curry Paste 100g', vi: 'Sốt cà ri đỏ hiệu Con Gà (Cock Brand) 100g', id: 'Pasta Kari Merah Cap Ayam (Cock Brand) 100g', th: 'พริกแกงเผ็ด 100g', zh: '有心紅咖哩100g' },
  'พริกแกงพะแนง有心咖哩醬100g': { en: 'Cock Brand Panang Curry Paste 100g', vi: 'Sốt cà ri khô Panang hiệu Con Gà 100g', id: 'Pasta Kari Panang Cap Ayam 100g', th: 'พริกแกงพะแนง 100g', zh: '有心咖哩醬100g' },
  'พริกแกงฮังเล料理包': { en: 'Northern Thai Kaeng Hung Ley Curry Paste Kit', vi: 'Gói gia vị nấu cà ri heo kiểu miền Bắc (Hung Ley)', id: 'Paket Bumbu Kari Hung Ley Khas Thailand Utara', th: 'พริกแกงฮังเล', zh: '料理包' },
  'พริกไทยป่น胡椒粉': { en: 'Ground White Pepper Powder', vi: 'Bột tiêu trắng', id: 'Lada Bubuk', th: 'พริกไทยป่น', zh: '胡椒粉' },
  'พริกน้ำเงี้ยว泰式料理包': { en: 'Northern Thai Nam Ngiao Rice Noodle Curry Kit', vi: 'Gói gia vị nấu bún nước lèo cay miền Bắc (Nam Ngiao)', id: 'Paket Bumbu Kuah Mie Nam Ngiao Khas Thailand Utara', th: 'พริกน้ำเงี้ยว', zh: '泰式料理包' },
  'พริกป่น辣椒粉': { en: 'Ground Red Pepper', vi: 'Ớt khô xay', id: 'Cabai Bubuk', th: 'พริกป่น', zh: '辣椒粉' },
  'พริกป่น辣椒粉14g': { en: 'Ground Red Pepper 14g', vi: 'Ớt khô xay 14g', id: 'Cabai Bubuk 14g', th: 'พริกป่น 14g', zh: '辣椒粉14g' },
  'พริกป่น辣椒粉50g': { en: 'Ground Red Pepper 50g', vi: 'Ớt khô xay 50g', id: 'Cabai Bubuk 50g', th: 'พริกป่น 50g', zh: '辣椒粉50g' },
  'พริกเผา513g泰式辣椒醬美寶牌': { en: 'Maepranom Thai Chili Paste 513g', vi: 'Ớt sa tế tôm kiểu Thái Maepranom 513g', id: 'Sambal Terasi 513g', th: 'พริกเผา แม่ประนอม 513g', zh: '泰式辣椒醬美寶牌' },
  'พริกเผา228g泰式辣椒醬美寶牌': { en: 'Maepranom Thai Chili Paste 228g', vi: 'Ớt sa tế tôm kiểu Thái Maepranom 228g', id: 'Sambal Terasi 228g', th: 'พริกเผา แม่ประนอม 228g', zh: '泰式辣椒醬美寶牌' },
  'พริกแห้ง辣椒干': { en: 'Dried Red Chilies', vi: 'Ớt khô nguyên quả', id: 'Cabai Kering', th: 'พริกแห้ง', zh: '辣椒干' },
  'ปุ้มปุ้ยปลาทอดSmiling辣醬炸魚': { en: 'Smiling Fish Fried Mackerel in Chili Sauce', vi: 'Cá nục chiên sốt ớt hiệu Cá Cười', id: 'Ikan Makarel Goreng Saus Cabai Cap Smiling Fish', th: 'ปุ้มปุ้ยปลาทอด', zh: 'Smiling辣醬炸魚' },
  'ปุ้มปุ้ยปลาราดพริกSmiling辣醬炸魚': { en: 'Smiling Fish Fried Mackerel with Chili', vi: 'Cá nục sốt ớt cay hiệu Cá Cười', id: 'Ikan Makarel Goreng Siram Cabai Cap Smiling Fish', th: 'ปุ้มปุ้ยปลาราดพริก', zh: 'Smiling辣醬炸魚' },
  'แป้งโกกิ油炸粉GOGI': { en: 'Gogi Tempura Flour', vi: 'Bột chiên giòn Gogi', id: 'Tepung Bumbu Krispi', th: 'แป้งโกกิ', zh: '油炸粉GOGI' },
  'แป้งทอดกรอบรสดี油炸粉': { en: 'RosDee Crispy Frying Flour', vi: 'Bột chiên xù', id: 'Tepung Bumbu Goreng Renyah RosDee', th: 'แป้งทอดกรอบรสดี', zh: '油炸粉' },
  'แป้งทอดกรอบรสดี油炸粉1': { en: 'RosDee Crispy Frying Flour', vi: 'Bột chiên xù', id: 'Tepung Bumbu Goreng Renyah RosDee', th: 'แป้งทอดกรอบรสดี', zh: '油炸粉' },
  'น้ำจิ้มไก่เด็กสมบูรณ์仁和園甜辣醬350': { en: 'Healthy Boy Sweet Chili Sauce 350g', vi: 'Sốt ớt ngọt chấm gà Healthy Boy 350g', id: 'Saus Sambal Bangkok Manis Healthy Boy 350g', th: 'น้ำจิ้มไก่เด็กสมบูรณ์ 350g', zh: '仁和園甜辣醬350' },
  'น้ำจิ้มไก่เด็กสมบูรณ์仁和園甜辣醬800': { en: 'Healthy Boy Sweet Chili Sauce 800g', vi: 'Sốt ớt ngọt chấm gà Healthy Boy 800g', id: 'Saus Sambal Bangkok Manis Healthy Boy 800g', th: 'น้ำจิ้มไก่เด็กสมบูรณ์ 800g', zh: '仁和園甜辣醬800' },
  'น้ำจิ้มไก่แม่พลอยMaeploy甜辣醬920': { en: 'Mae Ploy Sweet Chili Sauce 920g', vi: 'Sốt ớt ngọt chấm gà Mae Ploy 920g', id: 'Saus Sambal Bangkok Manis Mae Ploy 920g', th: 'น้ำจิ้มไก่แม่พลอย 920g', zh: 'Maeploy甜辣醬920' },
  'น้ำจิ้มไก่แม่พลอยMaeploy甜辣醬350': { en: 'Mae Ploy Sweet Chili Sauce 350g', vi: 'Sốt ớt ngọt chấm gà Mae Ploy 350g', id: 'Saus Sambal Bangkok Manis Mae Ploy 350g', th: 'น้ำจิ้มไก่แม่พลอย 350g', zh: 'Maeploy甜辣醬350' },
  'น้ำจิ้มสุกี้ สูตรกวางตุ้ง潘泰火鍋醬730': { en: 'Pantai Sukiyaki Sauce Cantonese Formula 730g', vi: 'Nước sốt lẩu Suki kiểu Quảng Đông Pantai 730g', id: 'Saus Suki Ala Kanton Pantai 730g', th: 'น้ำจิ้มสุกี้ สูตรกวางตุ้ง พันท้าย 730g', zh: '潘泰火鍋醬730' },
  'น้ำจิ้มสุกี้ สูตรกวางตุ้ง潘泰火鍋醬300': { en: 'Pantai Sukiyaki Sauce Cantonese Formula 300g', vi: 'Nước sốt lẩu Suki kiểu Quảng Đông Pantai 300g', id: 'Saus Suki Ala Kanton Pantai 300g', th: 'น้ำจิ้มสุกี้ สูตรกวางตุ้ง พันท้าย 300g', zh: '潘泰火鍋醬300' },
  'น้ำจิ้มสุกี้泰式甜辣醬': { en: 'Thai Sukiyaki Hot Pot Sauce', vi: 'Nước sốt lẩu Suki Thái', id: 'Saus Suki Hotpot Thailand', th: 'น้ำจิ้มสุกี้', zh: '泰式甜辣醬' },
  'น้ำจิ้มสุกี้สุรีย์素麗火鍋沾醬780': { en: 'Suree Sukiyaki Sauce 780g', vi: 'Sốt lẩu chấm Suki Suree 780g', id: 'Saus Suki Suree 780g', th: 'น้ำจิ้มสุกี้สุรีย์ 780g', zh: '素麗火鍋沾醬780' },
  'น้ำจิ้มสุกี้สุรีย์素麗火鍋醬300': { en: 'Suree Sukiyaki Sauce 300g', vi: 'Sốt lẩu chấm Suki Suree 300g', id: 'Saus Suki Suree 300g', th: 'น้ำจิ้มสุกี้สุรีย์ 300g', zh: '素麗火鍋醬300' },
  'น้ำตาลมะพร้าวกระปุก棕櫚糖': { en: 'Coconut Palm Sugar Tub', vi: 'Đường thốt nốt', id: 'Gula Aren', th: 'น้ำตาลมะพร้าวกระปุก', zh: '棕櫚糖' },
  'น้ำตาลมะพร้าวถุง椰糖1000': { en: 'Coconut Palm Sugar Bag 1000g', vi: 'Đường dừa dạng túi 1000g', id: 'Gula Kelapa Kemasan Kantong 1000g', th: 'น้ำตาลมะพร้าวถุง 1000g', zh: '椰糖1000' },
  'น้ำตาลมะพร้าวถุง椰糖500': { en: 'Coconut Palm Sugar Bag 500g', vi: 'Đường dừa dạng túi 500g', id: 'Gula Kelapa Kemasan Kantong 500g', th: 'น้ำตาลมะพร้าวถุง 500g', zh: '椰糖500' },
  'น้ำใบหญ้านาง葉菜汁': { en: 'Yanang Leaf Extract Juice', vi: 'Nước cốt lá sương sâm', id: 'Sari Daun Yanang', th: 'น้ำใบหญ้านาง', zh: '葉菜汁' },
  'น้ำปลาทิพย์รส味露300': { en: 'Tiparos Fish Sauce 300ml', vi: 'Nước mắm Tiparos 300ml', id: 'Kecap Ikan Tiparos 300ml', th: 'น้ำปลาทิพย์รส 300ml', zh: '味露300' },
  'น้ำปลาทิพย์รส味露4500': { en: 'Tiparos Fish Sauce 4500ml', vi: 'Nước mắm Tiparos 4500ml', id: 'Kecap Ikan Tiparos 4500ml', th: 'น้ำปลาทิพย์รส 4500ml', zh: '味露4500' },
  'น้ำปลาทิพย์รส味露700': { en: 'Tiparos Fish Sauce 700ml', vi: 'Nước mắm Tiparos 700ml', id: 'Kecap Ikan Tiparos 700ml', th: 'น้ำปลาทิพย์รส 700ml', zh: '味露700' },
  'น้ำปลาแท้ กุ้ง魚露700': { en: 'Premium Fish Sauce 700ml', vi: 'Nước mắm cốt hiệu Con Tôm 700ml', id: 'Kecap Ikan Asli Cap Udang 700ml', th: 'น้ำปลาแท้ กุ้ง 700ml', zh: '魚露700' },
  'น้ำปลาแท้ ปลาหมึก魷魚魚露700': { en: 'Squid Brand Fish Sauce 700ml', vi: 'Nước mắm hiệu Con Mực 700ml', id: 'Kecap Ikan Cap Cumi-Cumi 700ml', th: 'น้ำปลาแท้ ปลาหมึก 700ml', zh: '魷魚魚露700' },
  'น้ำปลานัมหงือ魚露500': { en: 'Nam Ngu Vietnam Fish Sauce 500ml', vi: 'Nước mắm Nam Ngư 500ml', id: 'Kecap Ikan Vietnam Nam Ngu 500ml', th: 'น้ำปลานัมหงือ 500ml', zh: '魚露500' },
  'น้ำปลาร้า แซ่บไมค์ZAB魚露': { en: 'Zab Mike Fermented Fish Sauce', vi: 'Nước mắm cá sặc lên men Zab Mike', id: 'Saus Ikan Fermentasi Zab Mike', th: 'น้ำปลาร้า แซ่บไมค์', zh: 'ZAB魚露' },
  'น้ำปลาร้า魚露300': { en: 'Fermented Fish Sauce 300ml', vi: 'Mắm nêm 300ml', id: 'Saus Ikan Fermentasi 300ml', th: 'น้ำปลาร้า 300ml', zh: '魚露300' },
  'น้ำปลาร้า魚露480': { en: 'Fermented Fish Sauce 480ml', vi: 'Mắm nêm 480ml', id: 'Saus Ikan Fermentasi 480ml', th: 'น้ำปลาร้า 480ml', zh: '魚露480' },
  'น้ำปลาร้า魚露700': { en: 'Fermented Fish Sauce 700ml', vi: 'Mắm nêm 700ml', id: 'Saus Ikan Fermentasi 700ml', th: 'น้ำปลาร้า 700ml', zh: '魚露700' },
  'น้ำมะขามเปียก酸子醬': { en: 'Tamarind Paste', vi: 'Sốt me', id: 'Asam Jawa Pasta', th: 'น้ำมะขามเปียก', zh: '酸子醬' },
  'น้ำมะนาว馬蜂橙汁700': { en: 'Kaffir Lime Juice 700ml', vi: 'Nước cốt chanh sần 700ml', id: 'Jus Jeruk Purut 700ml', th: 'น้ำมะนาว 700ml', zh: '馬蜂橙汁700' },
  'น้ำมะนาว馬蜂橙汁300': { en: 'Kaffir Lime Juice 300ml', vi: 'Nước cốt chanh sần 300ml', id: 'Jus Jeruk Purut 300ml', th: 'น้ำมะนาว 300ml', zh: '馬蜂橙汁300' },
  'ปลากระป๋อง沙丁魚': { en: 'Canned Sardines', vi: 'Cá mòi đóng hộp', id: 'Sardin Kaleng', th: 'ปลากระป๋อง', zh: '沙丁魚' },
  'ปลากระป๋องคั่วกลิ้ง鯖魚調味醬1': { en: 'Canned Mackerel in Khua Kling Southern Thai Curry Sauce', vi: 'Cá nục sốt cà ri Khua Kling kiểu miền Nam Thái Lan', id: 'Makarel Kaleng Bumbu Kari Khua Kling', th: 'ปลากระป๋องคั่วกลิ้ง', zh: '鯖魚調味醬' },
  'ปลากระป๋องคั่วกลิ้ง鯖魚調味醬2': { en: 'Canned Mackerel in Khua Kling Southern Thai Curry Sauce', vi: 'Cá nục sốt cà ri Khua Kling kiểu miền Nam Thái Lan', id: 'Makarel Kaleng Bumbu Kari Khua Kling', th: 'ปลากระป๋องคั่วกลิ้ง', zh: '鯖魚調味醬' },
  'ปลาร้าน้ำปู魚露350': { en: 'Fermented Fish Sauce with Crab Paste 350ml', vi: 'Mắm ba khía 350ml', id: 'Saus Plara Kombinasi Pasta Kepiting 350ml', th: 'ปลาร้าน้ำปู 350ml', zh: '魚露350' },
  'ปลาร้าส้มตำรสปู魚露480': { en: 'Fermented Fish Sauce for Som Tam Crab Flavor 480ml', vi: 'Nước mắm nấu gỏi đu đủ vị cua 480ml', id: 'Saus Plara Som Tam Rasa Kepiting 480ml', th: 'ปลาร้าส้มตำรสปู 480ml', zh: '魚露480' },
  'น้ำส้มสายชู金山醋大': { en: 'Golden Mountain Distilled Vinegar', vi: 'Giấm tiệt trùng hiệu Núi Vàng Golden Mountain', id: 'Cuka Fermentasi Golden Mountain', th: 'น้ำส้มสายชูภูเขาทอง', zh: '金山醋' },
  'น้ำมันพืชองุ่น沙拉油': { en: 'Angoon Soybean Cooking Oil', vi: 'Dầu ăn đậu nành hiệu Ngôi Sao', id: 'Minyak Goreng Kedelai Angoon', th: 'น้ำมันพืชองุ่น', zh: '沙拉油' },
  'ดีขวด牛膽汁': { en: 'Bottled Beef Bile', vi: 'Mật bò đóng chai', id: 'Empedu Sapi Botol', th: 'ดีขวด', zh: '牛膽汁' },
  'ต้มยำสำเร็จ有心辣椒醬454': { en: 'Maepranom Tom Yum Paste 454g', vi: 'Cốt súp Tom Yum ăn liền Maepranom 454g', id: 'Bumbu Pasta Tom Yum Instan Maepranom 454g', th: 'ต้มยำสำเร็จ 454g', zh: '有心辣椒醬454' },
  'ต้มยำสำเร็จ有心辣椒醬227': { en: 'Maepranom Tom Yum Paste 227g', vi: 'Cốt súp Tom Yum ăn liền Maepranom 227g', id: 'Bumbu Pasta Tom Yum Instan Maepranom 227g', th: 'ต้มยำสำเร็จ 227g', zh: '有心辣椒醬227' },
  'เต้าเจี้ยวเล็ก仁和園豆瓣醬350': { en: 'Healthy Boy Soybean Paste 350g', vi: 'Tương hột Healthy Boy 350g', id: 'Tauco Healthy Boy 350g', th: 'เต้าเจี้ยวเล็ก 350g', zh: '仁和園豆瓣醬350' },
  'เต้าเจี้ยวเล็ก仁和園豆瓣醬800': { en: 'Healthy Boy Soybean Paste 800g', vi: 'Tương hột Healthy Boy 800g', id: 'Tauco Healthy Boy 800g', th: 'เต้าเจี้ยวเล็ก 800g', zh: '仁和園豆瓣醬800' },
  'นมข้นหวาน三花煉乳': { en: 'Carnation Sweetened Condensed Milk', vi: 'Sữa đặc có đường Carnation', id: 'Susu Kental Manis Carnation', th: 'นมข้นหวาน สาม花', zh: '三花煉乳' },
  'นมข้นหวาน瑪麗煉乳': { en: 'Mali Sweetened Condensed Milk', vi: 'Sữa đặc có đường Mali', id: 'Susu Kental Manis Mali', th: 'นมข้นหวาน มะลิ', zh: '瑪麗煉乳' },
  'ซีอิ๊วขาว ขวดแก้ว仁和園醬油300': { en: 'Healthy Boy Light Soy Sauce 300g', vi: 'Nước tương Thượng Hạng Healthy Boy 300g', id: 'Kecap Asin Healthy Boy 300g', th: 'ซีอิ๊วขาว ขวดแก้ว 300g', zh: '仁和園醬油300' },
  'ซีอิ๊วขาว ขวดแก้ว仁和園醬油700': { en: 'Healthy Boy Light Soy Sauce 700g', vi: 'Nước tương Thượng Hạng Healthy Boy 700g', id: 'Kecap Asin Healthy Boy 700g', th: 'ซีอิ๊วขาว ขวดแก้ว 700g', zh: '仁和園醬油700' },
  'ซีอิ๊วดำเวียดนาม上等海鮮醬': { en: 'Vietnam Dark Soy Sauce', vi: 'Hắc xì dầu Việt Nam', id: 'Kecap Hitam Vietnam', th: 'ซีอิ๊วดำเวียดนาม', zh: '上等海鮮醬' },
  'ซีอิ๊วดำใหญ่仁和園醬油274': { en: 'Healthy Boy Black Sweet Soy Sauce 274ml', vi: 'Hắc xì dầu ngọt Healthy Boy 274ml', id: 'Kecap Manis Hitam Healthy Boy 274ml', th: 'ซีอิ๊วดำใหญ่ 274ml', zh: '仁和園醬油274' },
  'ซีอิ๊วดำใหญ่仁和園醬油940': { en: 'Healthy Boy Black Sweet Soy Sauce 940g', vi: 'Hắc xì dầu ngọt Healthy Boy 940g', id: 'Kecap Manis Hitam Healthy Boy 940g', th: 'ซีอิ๊วดำใหญ่ 940g', zh: '仁和園醬油940' },
  'เม็ดสาคู西谷米': { en: 'Tapioca Pearls', vi: 'Bột báng', id: 'Sagu Mutiara', th: 'เม็ดสาคู', zh: '西谷米' },
  'เม็ดสาคู西谷米1': { en: 'Tapioca Pearls', vi: 'Bột báng', id: 'Sagu Mutiara', th: 'เม็ดสาคู', zh: '西谷米' },
  'แมงดาขวด明拉醬': { en: 'Mangda Essence', vi: 'Nước sốt tinh dầu cà cuống', id: 'Saus Esens Kumbang Air', th: 'แมงดาขวด', zh: '明拉醬' },
  'รสดีกระเพราGaPao調味粉': { en: 'RosDee Pad Kra Pao Seasoning Powder', vi: 'Bột gia vị xào húng quế RosDee', id: 'Bumbu Bubuk Tumis Kemangi RosDee', th: 'รสดีกะเพรา', zh: 'GaPao調味粉' },
  'รสดีพะโล้PALO': { en: 'RosDee Pa-Lo Seasoning Powder', vi: 'Bột gia vị thịt kho tàu RosDee', id: 'Bumbu Bubuk Kuah Semur (Palo) RosDee', th: 'รสดีพะโล้', zh: 'PALO' },
  'รสดีหมู豬肉調味粉400': { en: 'RosDee Pork Seasoning Powder 400g', vi: 'Bột súp heo RosDee 400g', id: 'Bumbu Bubuk Rasa Babi RosDee 400g', th: 'รสดีหมู 400', zh: '豬肉調味粉400' },
  'รสดีหมู豬肉調味粉900': { en: 'RosDee Pork Seasoning Powder 900g', vi: 'Bột súp heo RosDee 900g', id: 'Bumbu Bubuk Rasa Babi RosDee 900g', th: 'รสดีหมู 900', zh: '豬肉調味粉900' },
  'รสดีหมู豬肉調味粉70': { en: 'RosDee Pork Seasoning Powder 70g', vi: 'Bột súp heo RosDee 70g', id: 'Bumbu Bubuk Rasa Babi RosDee 70g', th: 'รสดีหมู 70', zh: '豬肉調味粉70' },
  'ลำไยกระป๋อง龍眼罐頭': { en: 'Canned Longan in Syrup', vi: 'Nhãn đóng hộp', id: 'Lengkeng Kaleng dalam Sirup', th: 'ลำไยกระป๋อง', zh: '龍眼罐頭' },
  'ลูกชิดกระป๋อง亞達子罐頭': { en: 'Canned Attap Seed', vi: 'Hạt thốt nốt đóng hộp', id: 'Kolang-Kaling Kaleng', th: 'ลูกชิดกระป๋อง', zh: '亞達子罐頭' },
  'ลูกชิดกระป๋อง洸榔罐頭': { en: 'Canned Kaong', vi: 'Hạt đác đóng hộp', id: 'Buah Aren Kaleng', th: 'ลูกชิดกระป๋อง', zh: '洸榔罐頭' },
  'ลูกตาลกระป๋อง白玉丹罐頭': { en: 'Canned Toddy Palm Slices', vi: 'Thốt nốt lát đóng hộp', id: 'Irisan Kelapa Laut Kaleng', th: 'ลูกตาลกระป๋อง', zh: '白玉丹罐頭' },
  'วุ้นเส้น米粉': { en: 'Glass Noodles', vi: 'Miến', id: 'Sohun', th: 'วุ้นเส้น', zh: '米粉' },
  'เส้นก๋วยเตี๋ยวเวียดนาม澱粉條': { en: 'Vietnamese Rice Noodles', vi: 'Bánh phở Việt Nam', id: 'Kway Teow Vietnam', th: 'เส้นก๋วยเตี๋ยวเวียดนาม', zh: '澱粉條' },
  'เส้นก๋วยเตี๋ยวเวียดนาม澱粉條3': { en: 'Vietnamese Rice Noodles', vi: 'Bánh phở Việt Nam', id: 'Kway Teow Vietnam', th: 'เส้นก๋วยเตี๋ยวเวียดนาม', zh: '澱粉條' },
  'เส้นขนมจีน澱粉條2': { en: 'Thai Rice Vermicelli Noodles', vi: 'Bún tươi thái', id: 'Bihun Beras Fresh', th: 'เส้นขนมจีน', zh: '澱粉條2' },
  'เส้นหมี่ขาว米粉': { en: 'White Rice Vermicelli', vi: 'Bún gạo trắng', id: 'Bihun Beras Putih', th: 'เส้นหมี่ขาว', zh: '米粉' },
  'หน่อไม้ดอง醃竹筍罐': { en: 'Canned Pickled Bamboo Shoots', vi: 'Măng chua đóng hộp', id: 'Rebung Rendam Kaleng', th: 'หน่อไม้ดองกระป๋อง', zh: '醃竹筍罐' },
  'หอยลายSmiling辣醬炸魚1': { en: 'Smiling Fish Crispy Fried Clams', vi: 'Ngao sốt cay Smiling Fish', id: 'Kerang Goreng Sambal Smiling Fish', th: 'หอยลายยิ้ม', zh: 'Smiling辣醬炸魚1' },
  'แห้วกระป๋อง悖齊罐頭': { en: 'Canned Water Chestnuts', vi: 'Củ năng đóng hộp', id: 'Manisan Dari Bengkuang Air Kaleng', th: 'แห้วกระป๋อง', zh: '悖齊罐頭' },
  'เฮลูบอย紅糖水': { en: 'Hale’s Blue Boy Red Syrup', vi: 'Siro đỏ Hale’s Blue Boy', id: 'Sirup Merah Hale’s Blue Boy', th: 'เฮลูบอยแดง', zh: '紅糖水' },
  'เฮลูบอย綠糖水': { en: 'Hale’s Blue Boy Green Syrup', vi: 'Siro xanh Hale’s Blue Boy', id: 'Sirup Hijau Hale’s Blue Boy', th: 'เฮลูบอยเขียว', zh: '綠糖水' },
  'มะเขือเปราะ水茄': { en: 'Thai Eggplant', vi: 'Cà pháo Thái', id: 'Terong Bulat Thai', th: 'มะเขือเปราะ', zh: '水茄' },
  'ก๋วยเตี๋ยวเส้นเล็ก白粿條': { en: 'Thin Rice Noodles', vi: 'Hủ tiếu sợi nhỏ', id: 'Kway Teow Potong Tipis', th: 'ก๋วยเตี๋ยวเส้นเล็ก', zh: '白粿條' },
  'น้ำพริกสด新鮮辣椒醬': { en: 'Fresh Chili Paste', vi: 'Ớt chưng tươi', id: 'Sambal Cabai Segar', th: 'น้ำพริกสด', zh: '新鮮辣椒醬' },
  'น้ำกระเทียมดอง蒜頭水': { en: 'Pickled Garlic Juice', vi: 'Nước tỏi ngâm', id: 'Air Bawang Putih Acar', th: 'น้ำกระเทียมดอง', zh: '蒜頭水' },
  'กระเพรา打拋': { en: 'Holy Basil', vi: 'Rau húng quế dũa', id: 'Daun Kemangi Suci', th: 'กระเพรา', zh: '打拋' },
  'ข้าวคั่ว糯米粉50g': { en: 'Toasted Rice Powder50g', vi: 'Thính gạo50g', id: 'Bubuk Beras Sangrai50g', th: 'ข้าวคั่ว50g', zh: '糯米粉50g' },
  'ข้าวคั่ว糯米粉25g': { en: 'Toasted Rice Powder25g', vi: 'Thính gạo25g', id: 'Bubuk Beras Sangrai25g', th: 'ข้าวคั่ว25g', zh: '糯米粉25g' },
  'ตุ๋นเนื้อยาจีน中藥燉牛肉': { en: 'Chinese Herbal Beef Stew Spice Pack', vi: 'Gói gia vị hầm bò thuốc bắc', id: 'Bumbu Sup Herbal Rempah Cina untuk Daging Sapi', th: 'ตุ๋นเนื้อยาจีน', zh: '中藥燉牛肉' },
  'ตุ๋นหมูน้ำข้น燉豬肉': { en: 'Concentrated Pork Stew Spice Pack', vi: 'Gói gia vị hầm thịt heo đậm đà', id: 'Bumbu Sup Semur Daging Babi Kental', th: 'ตุ๋นหมูน้ำข้น', zh: '燉豬肉' },
  'ตะไคร้ใบมะกรูด冬蔭': { en: 'Tom Yum Herb Set', vi: 'Set gia vị Tom Yum', id: 'Paket Rempah Tom Yum', th: 'ตะไคร้ใบมะกรูด', zh: '冬蔭' },
  'ปลาหมึกแห้ง魷魚乾': { en: 'Dried Squid', vi: 'Mực khô', id: 'Cumi Kering', th: 'ปลาหมึกแห้ง', zh: '魷魚乾' },
  'ปลาแห้ง蛇紋魚': { en: 'Dried Striped Snakehead Fish', vi: 'Cá lóc khô', id: 'Ikan Gabus Kering', th: 'ปลาแห้ง', zh: '蛇紋魚' },
  'พริกไทยขาว白胡椒粒': { en: 'White Peppercorns', vi: 'Tiêu hạt trắng', id: 'Lada Putih Butiran', th: 'พริกไทยขาว', zh: '白胡椒粒' },
  'พริกไทยดำ黑胡椒粒': { en: 'Black Peppercorns', vi: 'Tiêu hạt đen', id: 'Lada Hitam Butiran', th: 'พริกไทยดำ', zh: '黑胡椒粒' },
  'พริกสด辣椒': { en: 'Fresh Chili', vi: 'Ớt tươi', id: 'Cabai Segar', th: 'พริกสด', zh: '辣椒' },
  'มะเขือเทศ蕃茄': { en: 'Tomato', vi: 'Cà chua', id: 'Tomat', th: 'มะเขือเทศ', zh: '蕃茄' },
  'มะนาว檸檬': { en: 'Lime', vi: 'Chanh xanh', id: 'Jeruk Nipis', th: 'มะนาว', zh: '檸檬' },
  'มะละกอ青木瓜': { en: 'Green Papaya', vi: 'Đu đủ xanh', id: 'Pepaya Muda', th: 'มะละกอ', zh: '青木瓜' },
  'กะทิผงสำเร็จรูป即溶椰漿粉': { en: 'Instant Coconut Milk Powder', vi: 'Bột cốt dừa', id: 'Serbuk Santan Kelapa', th: 'กะทิผงสำเร็จรูป', zh: '即溶椰漿粉' },

 

  // ── 酒 Alcohol ────────────────────────────────────────────────────
  'เบียร์ช้าง大象啤酒': { en: 'Chang Beer', vi: 'Bia Chang (Bia Voi Thái Lan)', id: 'Bir Chang', th: 'เบียร์ช้าง', zh: '大象啤酒' },
  'เบียร์ไต้หวัน金牌啤酒': { en: 'Taiwan Gold Medal Beer', vi: 'Bia Taiwan Beer Gold Medal', id: 'Bir Taiwan Gold Medal', th: 'เบียร์ไต้หวัน', zh: '金牌啤酒' },
  'เบียร์สิงห์泰國勝獅啤酒': { en: 'Singha Beer', vi: 'Bia Singha', id: 'Bir Singha', th: 'เบียร์สิงห์', zh: '泰國勝獅啤酒' },
  'สปายคลาสสิคSpy氣泡酒': { en: 'Spy Wine Cooler Classic', vi: 'Rượu trái cây Spy Classic', id: 'Cooler Anggur Spy Klasik', th: 'สปายคลาสสิค', zh: 'Spy氣泡酒' },
  'สปายเรดSpy氣泡酒': { en: 'Spy Wine Cooler Red', vi: 'Rượu trái cây Spy Red', id: 'Cooler Anggur Spy Merah', th: 'สปายเรด', zh: 'Spy氣泡酒' },
  'ไวน์玫瑰紅酒': { en: 'Rosé Wine', vi: 'Rượu vang hồng', id: 'Anggur Merah Rosé', th: 'ไวน์', zh: '玫瑰紅酒' },
  'ไวน์ขาว58金高': { en: '58% Kinmen Kaoliang Liquor', vi: 'Rượu Cao Lương Kim Môn 58 độ', id: 'Arak Putih Kinmen Kaoliang 58%', th: 'ไวน์ขาว', zh: '58金高' },
  'แสงโสมแบน泰國皇家': { en: 'SangSom Special Rum300ml', vi: 'Rượu SangSom Thái300ml', id: 'Rum SangSom Thailand300ml', th: 'แสงโสมแบน300ml', zh: '泰國皇家300ml' },
  'แสงโสมแบน0.7L泰國皇家': { en: 'SangSom Special Rum700ml', vi: 'Rượu SangSom Thái700ml', id: 'Rum SangSom Thailand700ml', th: 'แสงโสมแบน700ml', zh: '泰國皇家700ml' },
  'หงทองกลม紅通酒': { en: 'Hong Thong Spirits', vi: 'Rượu Hong Thong Thái', id: 'Wiski Hong Thong Thailand', th: 'หงทองกลม', zh: '紅通酒' },
  'เหล้า40ดีกรี泰國米酒農開': { en: 'Thai White Spirits 40 Degrees', vi: 'Rượu nếp trắng Thái 40 độ Nong Khai', id: 'Arak Putih Thailand 40 Persen', th: 'เหล้า 40 ดีกรี', zh: '泰國米酒農開' },
  'เหล้าขาว南都': { en: 'Nan Du White Liquor', vi: 'Rượu trắng Nam Đô', id: 'Arak Putih Nan Du', th: 'เหล้าขาว', zh: '南都' },
  'เหล้าเสือ紅虎': { en: 'Tiger Red Liquor', vi: 'Rượu hổ đỏ', id: 'Arak Macan Merah', th: 'เหล้าเสือ', zh: '紅虎' },
  'เบียร์ 3 กระป๋อง金牌啤酒3罐': { en: 'Taiwan Gold Medal Beer (3 Cans)', vi: 'Bia Taiwan Gold Medal (3 lon)', id: 'Bir Taiwan Gold Medal (3 Kaleng)', th: 'เบียร์ 3 กระป๋อง', zh: '金牌啤酒3罐' },



  // ── 清潔保養品 Hygiene & Beauty ───────────────────────────────────
  'กันแดดผู้ชายNivea精華液': { en: 'Nivea Men Sunscreen Serum', vi: 'Tinh chất chống nắng Nivea Men', id: 'Serum Tabir Surya Nivea Men', th: 'กันแดดผู้ชาย', zh: 'Nivea精華液' },
  'ซีซีครีมCathyDollCC霜': { en: 'Cathy Doll CC Cream', vi: 'Kem CC Cathy Doll', id: 'Cathy Doll CC Cream', th: 'ซีซีครีม', zh: 'CathyDollCC霜' },
  'ซีซีครีมยกกล่องCathyDollCC霜盒': { en: 'Cathy Doll CC Cream (Box)', vi: 'Kem CC Cathy Doll (Hộp)', id: 'Cathy Doll CC Cream (Box)', th: 'ซีซีครีมยกกล่อง', zh: 'CathyDollCC霜盒' },
  'ซีซีครีมCathyDollCC霜1': { en: 'Cathy Doll CC Cream', vi: 'Kem CC Cathy Doll', id: 'Cathy Doll CC Cream', th: 'ซีซีครีม', zh: 'CathyDollCC霜' },
  'ซีซีครีมยกกล่องCathyDollCC霜盒1': { en: 'Cathy Doll CC Cream (Box)', vi: 'Kem CC Cathy Doll (Hộp)', id: 'Cathy Doll CC Cream (Box)', th: 'ซีซีครีมยกกล่อง', zh: 'CathyDollCC霜盒' },
  'แชมพูHead&Sholders-Shampoo': { en: 'Head & Shoulders Shampoo', vi: 'Dầu gội Head & Shoulders', id: 'Sampo Head & Shoulders', th: 'แชมพู', zh: 'Head&Sholders-Shampoo' },
  'แชมพูHead&Sholders-Shampoo1': { en: 'Head & Shoulders Shampoo', vi: 'Dầu gội Head & Shoulders', id: 'Sampo Head & Shoulders', th: 'แชมพู', zh: 'Head&Sholders-Shampoo' },
  'แชมพูHead&Sholders-Shampoo2': { en: 'Head & Shoulders Shampoo', vi: 'Dầu gội Head & Shoulders', id: 'Sampo Head & Shoulders', th: 'แชมพู', zh: 'Head&Sholders-Shampoo' },
  'แชมพูHead&Sholders-Shampoo3': { en: 'Head & Shoulders Shampoo', vi: 'Dầu gội Head & Shoulders', id: 'Sampo Head & Shoulders', th: 'แชมพู', zh: 'Head&Sholders-Shampoo' },
  'แชมพูHead&Sholders-Shampoo4': { en: 'Head & Shoulders Shampoo', vi: 'Dầu gội Head & Shoulders', id: 'Sampo Head & Shoulders', th: 'แชมพู', zh: 'Head&Sholders-Shampoo' },
  'แชมพูHead&Sholders-Shampoo5': { en: 'Head & Shoulders Shampoo', vi: 'Dầu gội Head & Shoulders', id: 'Sampo Head & Shoulders', th: 'แชมพู', zh: 'Head&Sholders-Shampoo' },
  'แชมพูSunsilkShampoo': { en: 'Sunsilk Shampoo', vi: 'Dầu gội Sunsilk', id: 'Sampo Sunsilk', th: 'แชมพู', zh: 'SunsilkShampoo' },
  'แชมพูSunsilkShampoo1': { en: 'Sunsilk Shampoo', vi: 'Dầu gội Sunsilk', id: 'Sampo Sunsilk', th: 'แชมพู', zh: 'SunsilkShampoo' },
  'แชมพูSunsilkShampoo2': { en: 'Sunsilk Shampoo', vi: 'Dầu gội Sunsilk', id: 'Sampo Sunsilk', th: 'แชมพู', zh: 'SunsilkShampoo' },
  'แชมพูSunsilkShampoo3': { en: 'Sunsilk Shampoo', vi: 'Dầu gội Sunsilk', id: 'Sampo Sunsilk', th: 'แชมพู', zh: 'SunsilkShampoo' },
  'แชมพูSunsilkShampoo4': { en: 'Sunsilk Shampoo', vi: 'Dầu gội Sunsilk', id: 'Sampo Sunsilk', th: 'แชมพู', zh: 'SunsilkShampoo' },
  'แชมพูClearShampoo': { en: 'Clear Shampoo', vi: 'Dầu gội Clear', id: 'Sampo Clear', th: 'แชมพู', zh: 'ClearShampoo' },
  'แชมพูClearShampoo1': { en: 'Clear Shampoo', vi: 'Dầu gội Clear', id: 'Sampo Clear', th: 'แชมพู', zh: 'ClearShampoo' },
  'แชมพูClearShampoo2': { en: 'Clear Shampoo', vi: 'Dầu gội Clear', id: 'Sampo Clear', th: 'แชมพู', zh: 'ClearShampoo' },
  'แชมพูClearShampoo3': { en: 'Clear Shampoo', vi: 'Dầu gội Clear', id: 'Sampo Clear', th: 'แชมพู', zh: 'ClearShampoo' },
  'แชมพูClearShampoo4': { en: 'Clear Shampoo', vi: 'Dầu gội Clear', id: 'Sampo Clear', th: 'แชมพู', zh: 'ClearShampoo' },
  'แชมพูClearShampoo5': { en: 'Clear Shampoo', vi: 'Dầu gội Clear', id: 'Sampo Clear', th: 'แชมพู', zh: 'ClearShampoo' },
  'เจลอโลSmooto蝸牛凝膠': { en: 'Smooto Aloe E Snail Gel', vi: 'Gel nha đam ốc sên Smooto', id: 'Smooto Aloe E Snail Gel', th: 'เจลอโล', zh: 'Smooto蝸牛凝膠' },
  'เจลอโลยกกล่องSmooto蝸牛凝膠盒': { en: 'Smooto Aloe E Snail Gel (Box)', vi: 'Gel nha đam ốc sên Smooto (Hộp)', id: 'Smooto Aloe E Snail Gel (Box)', th: 'เจลอโลยกกล่อง', zh: 'Smooto蝸牛凝膠盒' },
  'สลิปปิ้งเซรั่มSmooto番茄精華': { en: 'Smooto Tomato Sleeping Serum', vi: 'Tinh chất ngủ cà chua Smooto', id: 'Smooto Tomato Sleeping Serum', th: 'สลิปปิ้งเซรั่ม', zh: 'Smooto番茄精華' },
  'สลิปปิ้งเซรั่มยกกล่องSmooto番茄精華盒': { en: 'Smooto Tomato Sleeping Serum (Box)', vi: 'Tinh chất ngủ cà chua Smooto (Hộp)', id: 'Smooto Tomato Sleeping Serum (Box)', th: 'สลิปปิ้งเซรั่มยกกล่อง', zh: 'Smooto番茄精華盒' },
  'กันแดดผู้ชายNIVEA防曬精華乳': { en: 'NIVEA Men Sunscreen Serum', vi: 'Tinh chất chống nắng nam NIVEA', id: 'Serum Tabir Surya Pria NIVEA', th: 'กันแดดผู้ชาย', zh: 'NIVEA防曬精華乳' },
  'ครีมนวดผมSunsilk護髮乳': { en: 'Sunsilk Hair Conditioner', vi: 'Dầu xả tóc Sunsilk', id: 'Kondisioner Rambut Sunsilk', th: 'ครีมนวดผม', zh: 'Sunsilk護髮乳' },
  'ครีมนวดผมSunsilk護髮乳1': { en: 'Sunsilk Hair Conditioner', vi: 'Dầu xả tóc Sunsilk', id: 'Kondisioner Rambut Sunsilk', th: 'ครีมนวดผม', zh: 'Sunsilk護髮乳' },
  'ครีมนวดผมSunsilk護髮乳2': { en: 'Sunsilk Hair Conditioner', vi: 'Dầu xả tóc Sunsilk', id: 'Kondisioner Rambut Sunsilk', th: 'ครีมนวดผม', zh: 'Sunsilk護髮乳' },
  'ครีมนวดผมSunsilk護髮乳3': { en: 'Sunsilk Hair Conditioner', vi: 'Dầu xả tóc Sunsilk', id: 'Kondisioner Rambut Sunsilk', th: 'ครีมนวดผม', zh: 'Sunsilk護髮乳' },
  'ครีมนวดผมSunsilk護髮乳4': { en: 'Sunsilk Hair Conditioner', vi: 'Dầu xả tóc Sunsilk', id: 'Kondisioner Rambut Sunsilk', th: 'ครีมนวดผม', zh: 'Sunsilk護髮乳' },
  'ครีมบำรุงผิOlay日霜': { en: 'Olay Day Cream', vi: 'Kem dưỡng ban ngày Olay', id: 'Krim Siang Olay', th: 'ครีมบำรุงผิ', zh: 'Olay日霜' },
  'ครีมบำรุงผิOlay日霜1': { en: 'Olay Day Cream', vi: 'Kem dưỡng ban ngày Olay', id: 'Krim Siang Olay', th: 'ครีมบำรุงผิ', zh: 'Olay日霜' },
  'ครีมบำรุงผิOlay日霜2': { en: 'Olay Day Cream', vi: 'Kem dưỡng ban ngày Olay', id: 'Krim Siang Olay', th: 'ครีมบำรุงผิ', zh: 'Olay日霜' },
  'ครีมบำรุงผิยกกล่องOlay日霜盒': { en: 'Olay Day Cream (Box)', vi: 'Kem dưỡng ban ngày Olay (Hộp)', id: 'Krim Siang Olay (Box)', th: 'ครีมบำรุงผิยกกล่อง', zh: 'Olay日霜盒' },
  'ครีมบำรุงผิยกกล่องOlay日霜盒1': { en: 'Olay Day Cream (Box)', vi: 'Kem dưỡng ban ngày Olay (Hộp)', id: 'Krim Siang Olay (Box)', th: 'ครีมบำรุงผิยกกล่อง', zh: 'Olay日霜盒' },
  'ครีมบำรุงผิยกกล่องOlay日霜盒2': { en: 'Olay Day Cream (Box)', vi: 'Kem dưỡng ban ngày Olay (Hộp)', id: 'Krim Siang Olay (Box)', th: 'ครีมบำรุงผิยกกล่อง', zh: 'Olay日霜盒' },
  'เซรั่มคุมมันGARNIER控油精華乳': { en: 'GARNIER Oil Control Serum Cream', vi: 'Tinh chất dưỡng kiềm dầu GARNIER', id: 'GARNIER Serum Cream Oil Control', th: 'เซรั่มคุมมัน', zh: 'GARNIER控油精華乳' },
  'เซรั่มครีมGARNIER防曬霜': { en: 'GARNIER Serum Cream Sunscreen', vi: 'Kem chống nắng tinh chất GARNIER', id: 'GARNIER Serum Cream Sunscreen', th: 'เซรั่มครีม', zh: 'GARNIER防曬霜' },
  'ครีมบำรุงซองGARNIER補': { en: 'GARNIER Nourishing Cream Sachet', vi: 'Kem dưỡng dạng gói GARNIER', id: 'GARNIER Krim Nutrisi Sachet', th: 'ครีมบำรุงซอง', zh: 'GARNIER補' },
  'สลีปปิ้งมาส์กGARNIER晚安面膜': { en: 'GARNIER Sleeping Mask', vi: 'Mặt nạ ngủ GARNIER', id: 'GARNIER Sleeping Mask', th: 'สลีปปิ้งมาส์ก', zh: 'GARNIER晚安面膜' },
  'ครีมบำรุงซองGARNIER補盒': { en: 'GARNIER Nourishing Cream Sachet (Box)', vi: 'Kem dưỡng dạng gói GARNIER (Hộp)', id: 'GARNIER Krim Nutrisi Sachet (Box)', th: 'ครีมบำรุงซอง', zh: 'GARNIER補盒' },
  'เซรั่มคุมมันยกกล่องGARNIER控油精華乳盒': { en: 'GARNIER Oil Control Serum (Box)', vi: 'Tinh chất dưỡng kiềm dầu GARNIER (Hộp)', id: 'GARNIER Serum Oil Control (Box)', th: 'เซรั่มคุมมันยกกล่อง', zh: 'GARNIER控油精華乳盒' },
  'เซรั่มครีมยกกล่องGARNIER防曬霜盒': { en: 'GARNIER Sunscreen Serum Cream (Box)', vi: 'Kem chống nắng tinh chất GARNIER (Hộp)', id: 'GARNIER Sunscreen Serum Cream (Box)', th: 'เซรั่มครีมยกกล่อง', zh: 'GARNIER防曬霜盒' },
  'สลีปปิ้งมาส์กยกกล่องGARNIER晚安面膜盒': { en: 'GARNIER Sleeping Mask (Box)', vi: 'Mặt nạ ngủ GARNIER (Hộp)', id: 'GARNIER Sleeping Mask (Box)', th: 'สลีปปิ้งมาส์กยกกล่อง', zh: 'GARNIER晚安面膜盒' },
  'ครีมบำรุงซองGARNIER精華乳霜': { en: 'GARNIER Essence Cream Sachet', vi: 'Kem tinh chất dạng gói GARNIER', id: 'GARNIER Essence Cream Sachet', th: 'ครีมบำรุงซอง', zh: 'GARNIER精華乳霜' },
  'เซรั่มผู้ชายNIVEA美白保濕乳': { en: 'NIVEA Men Whitening & Moisturizing Serum', vi: 'Tinh chất dưỡng trắng ẩm nam NIVEA', id: 'Serum Pria NIVEA Whitening & Moisturizing', th: 'เซรั่มผู้ชาย', zh: 'NIVEA美白保濕乳' },
  'ครีมบำรุงผิวNIVEA滋潤保養霜': { en: 'NIVEA Creme Moisturizer', vi: 'Kem dưỡng ẩm da NIVEA', id: 'Krim Pelembap NIVEA', th: 'ครีมบำรุงผิว', zh: 'NIVEA滋潤保養霜' },
  'ครีมกันแดดNivea精華乳霜': { en: 'Nivea Sunscreen Serum Cream', vi: 'Kem tinh chất chống nắng Nivea', id: 'Krim Serum Tabir Surya Nivea', th: 'ครีมกันแดด', zh: 'Nivea精華乳霜' },
  'โฟมล้างหน้าNIVEA抗痘洗面乳': { en: 'NIVEA Anti-Acne Facial Foam', vi: 'Sữa rửa mặt ngừa mụn NIVEA', id: 'NIVEA Anti-Acne Facial Foam', th: 'โฟมล้างหน้า', zh: 'NIVEA抗痘洗面乳' },
  'ผสมสารกันแดดGARNIER美白精華乳': { en: 'GARNIER Whitening Serum with UV Filter', vi: 'Tinh chất dưỡng trắng chống nắng GARNIER', id: 'GARNIER Serum Whitening UV', th: 'ผสมสารกันแดด', zh: 'GARNIER美白精華乳' },
  'เซรั่มผู้ชายยกกล่องNIVEA美白保濕乳盒': { en: 'NIVEA Men Whitening Serum (Box)', vi: 'Tinh chất dưỡng trắng nam NIVEA (Hộp)', id: 'Serum Pria NIVEA Whitening (Box)', th: 'เซรั่มผู้ชายยกกล่อง', zh: 'NIVEA美白保濕乳盒' },
  'กันแดดผู้ชายยกกล่องNivea精華液盒': { en: 'Nivea Men Sunscreen Serum (Box)', vi: 'Tinh chất chống nắng nam Nivea (Hộp)', id: 'Serum Tabir Surya Pria Nivea (Box)', th: 'กันแดดผู้ชายยกกล่อง', zh: 'Nivea精華液盒' },
  'กันแดดผู้ชายยกกล่องNIVEA防曬精華乳盒': { en: 'NIVEA Men Sunscreen Serum Cream (Box)', vi: 'Kem tinh chất chống nắng nam NIVEA (Hộp)', id: 'Krim Serum Tabir Surya Pria NIVEA (Box)', th: 'กันแดดผู้ชายยกกล่อง', zh: 'NIVEA防曬精華乳盒' },
  'ครีมบำรุงผิวยกกล่องNIVEA滋潤保養霜盒': { en: 'NIVEA Moisturizing Creme (Box)', vi: 'Kem dưỡng ẩm NIVEA (Hộp)', id: 'Krim Pelembap NIVEA (Box)', th: 'ครีมบำรุงผิวยกกล่อง', zh: 'NIVEA滋潤保養霜盒' },
  'ครีมกันแดดยกกล่องNivea精華乳霜盒': { en: 'Nivea Sunscreen Serum Cream (Box)', vi: 'Kem tinh chất chống nắng Nivea (Hộp)', id: 'Krim Serum Tabir Surya Nivea (Box)', th: 'ครีมกันแดดยกกล่อง', zh: 'Nivea精華乳霜盒' },
  'โฟมล้างหน้ายกกล่องNIVEA抗痘洗面乳盒': { en: 'NIVEA Anti-Acne Facial Foam (Box)', vi: 'Sữa rửa mặt ngừa mụn NIVEA (Hộp)', id: 'NIVEA Anti-Acne Facial Foam (Box)', th: 'โฟมล้างหน้ายกกล่อง', zh: 'NIVEA抗痘洗面乳盒' },
  'ผสมสารกันแดดยกกล่องGARNIER美白精華乳盒': { en: 'GARNIER Whitening Serum with UV Filter (Box)', vi: 'Tinh chất dưỡng trắng chống nắng GARNIER (Hộp)', id: 'GARNIER Serum Whitening UV (Box)', th: 'ผสมสารกันแดดยกกล่อง', zh: 'GARNIER美白精華乳盒' },
  'ครีมกลางวันPonds亮白日霜': { en: 'Ponds Brightening Day Cream', vi: 'Kem dưỡng sáng da ban ngày Ponds', id: 'Ponds Brightening Day Cream', th: 'ครีมกลางวัน', zh: 'Ponds亮白日霜' },
  'ครีมบำรุงซองPOND\'S日霜盒': { en: 'POND\'S Day Cream Sachet (Box)', vi: 'Kem dưỡng ban ngày dạng gói POND\'S (Hộp)', id: 'POND\'S Day Cream Sachet (Box)', th: 'ครีมบำรุงซอง', zh: 'POND\'S日霜盒' },
  'ครีมกลางวันPonds亮白保濕日霜': { en: 'Ponds Brightening & Moisturizing Day Cream', vi: 'Kem dưỡng ẩm sáng da ban ngày Ponds', id: 'Ponds Brightening & Moisturizing Day Cream', th: 'ครีมกลางวัน', zh: 'Ponds亮白保濕日霜' },
  'ครีมกลางวันยกกล่องPonds亮白日霜盒': { en: 'Ponds Brightening Day Cream (Box)', vi: 'Kem dưỡng sáng da ban ngày Ponds (Hộp)', id: 'Ponds Brightening Day Cream (Box)', th: 'ครีมกลางวันยกกล่อง', zh: 'Ponds亮白日霜盒' },
  'ครีมกลางวันยกกล่องPonds亮白保濕日霜盒': { en: 'Ponds Brightening & Moisturizing Day Cream (Box)', vi: 'Kem dưỡng ẩm sáng da ban ngày Ponds (Hộp)', id: 'Ponds Brightening & Moisturizing Day Cream (Box)', th: 'ครีมกลางวันยกกล่อง', zh: 'Ponds亮白保濕日霜盒' },
  'เซรั่มคุมมันVaseline控油精華乳': { en: 'Vaseline Oil Control Serum Cream', vi: 'Tinh chất dưỡng kiềm dầu Vaseline', id: 'Vaseline Serum Cream Oil Control', th: 'เซรั่มคุมมัน', zh: 'Vaseline控油精華乳' },
  'เซรั่มคุมมันยกกล่องVaseline控油精華乳盒': { en: 'Vaseline Oil Control Serum Cream (Box)', vi: 'Tinh chất dưỡng kiềm dầu Vaseline (Hộp)', id: 'Vaseline Serum Cream Oil Control (Box)', th: 'เซรั่มคุมมันยกกล่อง', zh: 'Vaseline控油精華乳盒' },
  'ครีมกลางคืนPonds晚霜': { en: 'Ponds Night Cream', vi: 'Kem dưỡng ban đêm Ponds', id: 'Ponds Night Cream', th: 'ครีมกลางคืน', zh: 'Ponds晚霜' },
  'ครีมอาบนํ้าLux沐浴乳': { en: 'Lux Body Wash', vi: 'Sữa tắm Lux', id: 'Sabun Mandi Cair Lux', th: 'ครีมอาบนํ้า', zh: 'Lux沐浴乳' },
  'ครีมอาบนํ้าLux沐浴乳1': { en: 'Lux Body Wash', vi: 'Sữa tắm Lux', id: 'Sabun Mandi Cair Lux', th: 'ครีมอาบนํ้า', zh: 'Lux沐浴乳' },
  'ครีมอาบนํ้าLux沐浴乳2': { en: 'Lux Body Wash', vi: 'Sữa tắm Lux', id: 'Sabun Mandi Cair Lux', th: 'ครีมอาบนํ้า', zh: 'Lux沐浴乳' },
  'ครีมอาบนํ้าLux沐浴乳3': { en: 'Lux Body Wash', vi: 'Sữa tắm Lux', id: 'Sabun Mandi Cair Lux', th: 'ครีมอาบนํ้า', zh: 'Lux沐浴乳' },
  'ครีมอาบนํ้าLux沐浴乳4': { en: 'Lux Body Wash', vi: 'Sữa tắm Lux', id: 'Sabun Mandi Cair Lux', th: 'ครีมอาบนํ้า', zh: 'Lux沐浴乳' },
  'ครีมอาบนํ้าLux沐浴乳5': { en: 'Lux Body Wash', vi: 'Sữa tắm Lux', id: 'Sabun Mandi Cair Lux', th: 'ครีมอาบนํ้า', zh: 'Lux沐浴乳' },
  'ครีมอาบนํ้าLux沐浴乳6': { en: 'Lux Body Wash', vi: 'Sữa tắm Lux', id: 'Sabun Mandi Cair Lux', th: 'ครีมอาบนํ้า', zh: 'Lux沐浴乳' },
  'โคโลญจน์50mlNivea體香劑': { en: 'Nivea Deodorant Cologne 50ml', vi: 'Xịt khử mùi Nivea 50ml', id: 'Nivea Deodorant Cologne 50ml', th: 'โคโลญจน์50ml', zh: 'Nivea體香劑' },
  'โคโลญจน์50mlNivea體香劑1': { en: 'Nivea Deodorant Cologne 50ml', vi: 'Xịt khử mùi Nivea 50ml', id: 'Nivea Deodorant Cologne 50ml', th: 'โคโลญจน์50ml', zh: 'Nivea體香劑' },
  'โคโลญจน์25mlNivea體香劑': { en: 'Nivea Deodorant Cologne 25ml', vi: 'Xịt khử mùi Nivea 25ml', id: 'Nivea Deodorant Cologne 25ml', th: 'โคโลญจน์25ml', zh: 'Nivea體香劑' },
  'แฟ๊บ洗衣粉': { en: 'Detergent Powder', vi: 'Bột giặt', id: 'Deterjen Bubuk', th: 'แฟ๊บ', zh: '洗衣粉' },
  'แฟ๊บ洗衣粉1': { en: 'Detergent Powder', vi: 'Bột giặt', id: 'Deterjen Bubuk', th: 'แฟ๊บ', zh: '洗衣粉' },
  'แฟ๊บ洗衣粉2': { en: 'Detergent Powder', vi: 'Bột giặt', id: 'Deterjen Bubuk', th: 'แฟ๊บ', zh: '洗衣粉' },
  'แฟ๊บ洗衣粉3': { en: 'Detergent Powder', vi: 'Bột giặt', id: 'Deterjen Bubuk', th: 'แฟ๊บ', zh: '洗衣粉' },
  'แฟ๊บ洗衣粉8': { en: 'Detergent Powder', vi: 'Bột giặt', id: 'Deterjen Bubuk', th: 'แฟ๊บ', zh: '洗衣粉' },
  'แฟ๊บ洗衣粉7': { en: 'Detergent Powder', vi: 'Bột giặt', id: 'Deterjen Bubuk', th: 'แฟ๊บ', zh: '洗衣粉' },
  'แฟ๊บ洗衣粉6': { en: 'Detergent Powder', vi: 'Bột giặt', id: 'Deterjen Bubuk', th: 'แฟ๊บ', zh: '洗衣粉' },
  'แฟ๊บ洗衣粉5': { en: 'Detergent Powder', vi: 'Bột giặt', id: 'Deterjen Bubuk', th: 'แฟ๊บ', zh: '洗衣粉' },
  'แฟ๊บ洗衣粉4': { en: 'Detergent Powder', vi: 'Bột giặt', id: 'Deterjen Bubuk', th: 'แฟ๊บ', zh: '洗衣粉' },
  'โฟมล้างหน้าNivea洗面乳3': { en: 'Nivea Facial Foam Cleanser', vi: 'Sữa rửa mặt Nivea', id: 'Sabun Cuci Muka Nivea', th: 'โฟมล้างหน้า Nivea', zh: 'Nivea洗面乳' },
  'โฟมล้างหน้าNivea洗面乳1': { en: 'Nivea Facial Foam Cleanser', vi: 'Sữa rửa mặt Nivea', id: 'Sabun Cuci Muka Nivea', th: 'โฟมล้างหน้า Nivea', zh: 'Nivea洗面乳' },
  'โฟมล้างหน้าNivea洗面乳': { en: 'Nivea Facial Foam Cleanser', vi: 'Sữa rửa mặt Nivea', id: 'Sabun Cuci Muka Nivea', th: 'โฟมล้างหน้า Nivea', zh: 'Nivea洗面乳' },
  'โฟมล้างหน้าNivea洗面乳2': { en: 'Nivea Facial Foam Cleanser', vi: 'Sữa rửa mặt Nivea', id: 'Sabun Cuci Muka Nivea', th: 'โฟมล้างหน้า Nivea', zh: 'Nivea洗面乳' },
  'โฟมล้างหน้าSmoothe洗面乳': { en: 'SmoothE Facial Foam Cleanser', vi: 'Sữa rửa mặt trị mụn dịu nhẹ SmoothE', id: 'Sabun Cuci Muka SmoothE', th: 'โฟมล้างหน้าSmoothE', zh: 'SmoothE洗面乳' },
  'โฟมล้างหน้าGarnier洗面乳': { en: 'Garnier Facial Foam Cleanser', vi: 'Sữa rửa mặt trị mụn dịu nhẹ Garnier', id: 'Sabun Cuci Muka Garnier', th: 'โฟมล้างหน้าGarnier', zh: 'Garnier洗面乳' },
  'แป้งฝุ่น12PLUS爽身粉': { en: '12 Plus Talcum Powder', vi: 'Phấn rôm', id: 'Bedak Tabur', th: 'แป้งฝุ่น 12PLUS', zh: '爽身粉' },
  'แป้งฝุ่น馬頭爽身粉': { en: 'St. Lukes Prickly Heat Powder', vi: 'Phấn mát trị rôm sẩy hiệu Đầu Ngựa', id: 'Bedak Dingin Anti Biang Keringat Cap Kepala Kuda', th: 'แป้งฝุ่น ตราม้า', zh: '馬頭爽身粉' },
  'แป้งฝุ่นBabi爽身粉3': { en: 'Babi Mild Baby Powder', vi: 'Phấn rôm cho bé Babi Mild', id: 'Bedak Bayi Babi Mild', th: 'แป้งฝุ่น Babi Mild', zh: 'Babi爽身粉' },
  'แป้งฝุ่นBabi爽身粉2': { en: 'Babi Mild Baby Powder', vi: 'Phấn rôm cho bé Babi Mild', id: 'Bedak Bayi Babi Mild', th: 'แป้งฝุ่น Babi Mild', zh: 'Babi爽身粉' },
  'แป้งฝุ่นBabi爽身粉1': { en: 'Babi Mild Baby Powder', vi: 'Phấn rôm cho bé Babi Mild', id: 'Bedak Bayi Babi Mild', th: 'แป้งฝุ่น Babi Mild', zh: 'Babi爽身粉' },
  'แป้งฝุ่นBabi爽身粉4': { en: 'Babi Mild Baby Powder', vi: 'Phấn rôm cho bé Babi Mild', id: 'Bedak Bayi Babi Mild', th: 'แป้งฝุ่น Babi Mild', zh: 'Babi爽身粉' },
  'แป้งฝุ่นBabi爽身粉': { en: 'Babi Mild Baby Powder', vi: 'Phấn rôm cho bé Babi Mild', id: 'Bedak Bayi Babi Mild', th: 'แป้งฝุ่น Babi Mild', zh: 'Babi爽身粉' },
  'แป้งฝุ่นCare爽身粉': { en: 'Care Baby Powder', vi: 'Phấn rôm cho bé Care', id: 'Bedak Bayi Care', th: 'แป้งฝุ่น Care', zh: '爽身粉' },
  'แป้งฝุ่นCare爽身粉2': { en: 'Care Baby Powder', vi: 'Phấn rôm cho bé Care', id: 'Bedak Bayi Care', th: 'แป้งฝุ่น Care', zh: '爽身粉' },
  'แป้งฝุ่นCare爽身粉1': { en: 'Care Baby Powder', vi: 'Phấn rôm cho bé Care', id: 'Bedak Bayi Care', th: 'แป้งฝุ่น Care', zh: '爽身粉' },
  'แป้งฝุ่นP爽身粉1': { en: 'Talcum Powder', vi: 'Phấn rôm', id: 'Bedak Tabur', th: 'แป้งฝุ่น', zh: '爽身粉' },
  'แป้งฝุ่นP爽身粉': { en: 'Talcum Powder', vi: 'Phấn rôm', id: 'Bedak Tabur', th: 'แป้งฝุ่น', zh: '爽身粉' },
  'แป้งฝุ่นP爽身粉4': { en: 'Talcum Powder', vi: 'Phấn rôm', id: 'Bedak Tabur', th: 'แป้งฝุ่น', zh: '爽身粉' },
  'แป้งฝุ่นP爽身粉2': { en: 'Talcum Powder', vi: 'Phấn rôm', id: 'Bedak Tabur', th: 'แป้งฝุ่น', zh: '爽身粉' },
  'แป้งฝุ่นP爽身粉3': { en: 'Talcum Powder', vi: 'Phấn rôm', id: 'Bedak Tabur', th: 'แป้งฝุ่น', zh: '爽身粉' },
  'แป้งพอนย์Ponds蜜粉1': { en: 'Ponds Magic Powder', vi: 'Phấn phủ dạng bột Ponds', id: 'Bedak Wajah Ponds Magic Powder', th: 'แป้งพอนด์ส', zh: 'Ponds蜜粉' },
  'แป้งพอนย์Ponds蜜粉': { en: 'Ponds Magic Powder', vi: 'Phấn phủ dạng bột Ponds', id: 'Bedak Wajah Ponds Magic Powder', th: 'แป้งพอนด์ส', zh: 'Ponds蜜粉' },
  'แป้งพอนย์Ponds蜜粉2': { en: 'Ponds Magic Powder', vi: 'Phấn phủ dạng bột Ponds', id: 'Bedak Wajah Ponds Magic Powder', th: 'แป้งพอนด์ส', zh: 'Ponds蜜粉' },
  'แป้งโยคี足粉': { en: 'Yokee Powder', vi: 'Phấn trị rôm sẩy', id: 'Bedak Kesehatan', th: 'แป้งโยคี', zh: '足粉' },
  'ปรับผ้านุ่มComfort 柔軟精': { en: 'Comfort Fabric Softener', vi: 'Nước xả vải Comfort', id: 'Pelembut Pakaian Comfort', th: 'ปรับผ้านุ่ม Comfort', zh: '柔軟精' },
  'ปรับผ้านุ่มComfort 柔軟精1': { en: 'Comfort Fabric Softener', vi: 'Nước xả vải Comfort', id: 'Pelembut Pakaian Comfort', th: 'ปรับผ้านุ่ม Comfort', zh: '柔軟精' },
  'ปรับผ้านุ่มComfort 柔軟精2': { en: 'Comfort Fabric Softener', vi: 'Nước xả vải Comfort', id: 'Pelembut Pakaian Comfort', th: 'ปรับผ้านุ่ม Comfort', zh: '柔軟精' },
  'ปรับผ้านุ่มComfort 柔軟精3': { en: 'Comfort Fabric Softener', vi: 'Nước xả vải Comfort', id: 'Pelembut Pakaian Comfort', th: 'ปรับผ้านุ่ม Comfort', zh: '柔軟精' },
  'ปรับผ้านุ่ม750mlDowny柔軟精2': { en: 'Downy Fabric Softene750mlr', vi: 'Nước xả vải Downy750ml', id: 'Pelembut Pakaian Downy750ml', th: 'ปรับผ้านุ่ม Downy750ml', zh: '柔軟精750ml' },
  'ปรับผ้านุ่ม750mlDowny柔軟精1': { en: 'Downy Fabric Softener750ml', vi: 'Nước xả vải Downy750ml', id: 'Pelembut Pakaian Downy750ml', th: 'ปรับผ้านุ่ม Downy750ml', zh: '柔軟精750ml' },
  'ปรับผ้านุ่ม750mlDowny柔軟精': { en: 'Downy Fabric Softener750ml', vi: 'Nước xả vải Downy750ml', id: 'Pelembut Pakaian Downy750ml', th: 'ปรับผ้านุ่ม Downy750ml', zh: '柔軟精750ml' },
  'ปรับผ้านุ่ม750mlDowny柔軟精大': { en: 'Downy Fabric Softener', vi: 'Nước xả vải Downy', id: 'Pelembut Pakaian Downy', th: 'ปรับผ้านุ่ม Downy', zh: '柔軟精' },
  'ปรับผ้านุ่มH柔軟精3': { en: 'Hygiene Fabric Softener', vi: 'Nước xả vải Hygiene', id: 'Pelembut Pakaian Hygiene', th: 'ปรับผ้านุ่ม Hygiene', zh: 'H柔軟精' },
  'ปรับผ้านุ่มH柔軟精2': { en: 'Hygiene Fabric Softener', vi: 'Nước xả vải Hygiene', id: 'Pelembut Pakaian Hygiene', th: 'ปรับผ้านุ่ม Hygiene', zh: 'H柔軟精' },
  'ปรับผ้านุ่มH柔軟精1': { en: 'Hygiene Fabric Softener', vi: 'Nước xả vải Hygiene', id: 'Pelembut Pakaian Hygiene', th: 'ปรับผ้านุ่ม Hygiene', zh: 'H柔軟精' },
  'น้ำยาบ้วนปาก漱口水1': { en: 'Mouthwash', vi: 'Nước súc miệng', id: 'Obat Kumur', th: 'น้ำยาบ้วนปาก', zh: '漱口水' },
  'น้ำยาบ้วนปาก漱口水': { en: 'Mouthwash', vi: 'Nước súc miệng', id: 'Obat Kumur', th: 'น้ำยาบ้วนปาก', zh: '漱口水' },
  'น้ำยาอนามัยMistine私密處清潔液': { en: 'Mistine Intimate Cleansing Lotion', vi: 'Dung dịch vệ sinh phụ nữ Mistine', id: 'Mistine Sabun Pembersih Kewanitaan', th: 'น้ำยาล้างจุดซ่อนเร้น Mistine', zh: 'Mistine私密處清潔液' },
  'น้ำยาอนามัยMistine私密處清潔液1': { en: 'Mistine Intimate Cleansing Lotion', vi: 'Dung dịch vệ sinh phụ nữ Mistine', id: 'Mistine Sabun Pembersih Kewanitaan', th: 'น้ำยาล้างจุดซ่อนเร้น Mistine', zh: 'Mistine私密處清潔液' },
  'เบบี้ออยล์Johnsons嬰兒油': { en: 'Johnsons Baby Oil', vi: 'Dầu dưỡng ẩm cho bé Johnsons Baby Oil', id: 'Minyak Bayi Johnsons Baby Oil', th: 'เบบี้ออยล์ Johnsons', zh: 'Johnsons嬰兒油' },
  'ทรีดเม้นCaring護髮油': { en: 'Caring Hair Treatment Oil', vi: 'Kem ủ tóc', id: 'Minyak Perawatan Rambut Caring', th: 'ทรีดเม้น Caring', zh: '護髮油' },
  'ทรีดเม้นCaring護髮油2': { en: 'Caring Hair Treatment Oil', vi: 'Kem ủ tóc', id: 'Minyak Perawatan Rambut Caring', th: 'ทรีดเม้น Caring', zh: '護髮油' },
  'ทรีดเม้นCaring護髮油3': { en: 'Caring Hair Treatment Oil', vi: 'Kem ủ tóc', id: 'Minyak Perawatan Rambut Caring', th: 'ทรีดเม้น Caring', zh: '護髮油' },
  'ทรีดเม้นCaring護髮油1': { en: 'Caring Hair Treatment Oil', vi: 'Kem ủ tóc', id: 'Minyak Perawatan Rambut Caring', th: 'ทรีดเม้น Caring', zh: '護髮油' },
  'ทรีดเม้นCaring護髮油Big': { en: 'Caring Hair Treatment Oil (Large)', vi: 'Kem ủ tóc(Cỡ lớn)', id: 'Minyak Perawatan Rambut Caring (Besar)', th: 'ทรีดเม้น Caring Big', zh: '護髮油Big' },
  'ดีดีครีมกันแดดJulas西瓜霜': { en: 'Julas Herb Watermelon DD Cream', vi: 'Kem chống nắng dưa hấu Julas Herb DD Cream', id: 'Krim Tabir Surya Semangka Julas Herb DD Cream', th: 'ดีดีครีมกันแดด Julas Herb', zh: 'Julas西瓜霜' },
  'บูสเตอร์เซรั่มJulas精華液': { en: 'Julas Herb Booster Serum', vi: 'Tinh chất dưỡng da Booster Serum Julas Herb', id: 'Serum Booster Julas Herb', th: 'บูสเตอร์เซรั่ม Julas Herb', zh: 'Julas精華液' },
  'บูสเตอร์เซรั่มJulas精華液1': { en: 'Julas Herb Booster Serum', vi: 'Tinh chất dưỡng da Booster Serum Julas Herb', id: 'Serum Booster Julas Herb', th: 'บูสเตอร์เซรั่ม Julas Herb', zh: 'Julas精華液' },
  'ดีดีครีมกันแดดยกกล่องJulas西瓜霜盒': { en: 'Julas Herb Watermelon DD Cream (Box)', vi: 'Kem chống nắng dưa hấu Julas Herb DD Cream (Hộp)', id: 'Krim Tabir Surya Semangka Julas Herb DD Cream (Box)', th: 'ดีดีครีมกันแดดยกกล่อง Julas Herb', zh: 'Julas西瓜霜盒' },
  'บูสเตอร์เซรั่มยกกล่องJulas精華液盒': { en: 'Julas Herb Booster Serum (Box)', vi: 'Tinh chất dưỡng da Booster Serum Julas Herb (Hộp)', id: 'Serum Booster Julas Herb (Box)', th: 'บูสเตอร์เซรั่มยกกล่อง Julas Herb', zh: 'Julas精華液盒' },
  'บูสเตอร์เซรั่มยกกล่องJulas精華液盒1': { en: 'Julas Herb Booster Serum (Box)', vi: 'Tinh chất dưỡng da Booster Serum Julas Herb (Hộp)', id: 'Serum Booster Julas Herb (Box)', th: 'บูสเตอร์เซรั่มยกกล่อง Julas Herb', zh: 'Julas精華液盒' },
  'ยาย้อมผมBerina A18黃金色染髮膏': { en: 'Berina Hair Color Cream A18 (Golden Blonde)', vi: 'Kem nhuộm tóc Berina A18 (Vàng kim)', id: 'Krim Pewarna Rambut Berina A18 (Golden Blonde)', th: 'ยาย้อมผมเบอริน่า A18', zh: 'Berina A18黃金色染髮膏' },
  'ยาย้อมผมBerina A21 淺灰色染髮膏': { en: 'Berina Hair Color Cream A21 (Light Grey)', vi: 'Kem nhuộm tóc Berina A21 (Xám khói nhạt)', id: 'Krim Pewarna Rambut Berina A21 (Light Grey)', th: 'ยาย้อมผมเบอริน่า A21', zh: 'Berina A21 淺灰色染髮膏' },
  'ยาสีฟัน กลิสเทอร์安麗牙膏': { en: 'Amway Glister Toothpaste', vi: 'Kem đánh răng Amway Glister', id: 'Pasta Gigi Amway Glister', th: 'ยาสีฟัน กลิสเทอร์', zh: '安麗牙膏' },
  'ยาสีฟัน黑人牌牙膏': { en: 'Darlie Toothpaste', vi: 'Kem đánh răng Darlie', id: 'Pasta Gigi Darlie', th: 'ยาสีฟันดาร์ลี่', zh: '黑人牌牙膏' },
  'ยาสีฟัน雙蓮牙膏': { en: 'Twin Lotus Herbal Toothpaste', vi: 'Kem đánh răng thảo dược Twin Lotus', id: 'Pasta Gigi Herbal Twin Lotus', th: 'ยาสีฟันดอกบัวคู่', zh: '雙蓮牙膏' },
  'ยาสีฟัน雙蓮牙膏1': { en: 'Twin Lotus Herbal Toothpaste', vi: 'Kem đánh răng thảo dược Twin Lotus', id: 'Pasta Gigi Herbal Twin Lotus', th: 'ยาสีฟันดอกบัวคู่', zh: '雙蓮牙膏' },
  'ยาสีฟัน雙蓮牙膏2': { en: 'Twin Lotus Herbal Toothpaste', vi: 'Kem đánh răng thảo dược Twin Lotus', id: 'Pasta Gigi Herbal Twin Lotus', th: 'ยาสีฟันดอกบัวคู่', zh: '雙蓮牙膏' },
  'ยาสีฟันColgate牙膏': { en: 'Colgate Toothpaste', vi: 'Kem đánh răng Colgate', id: 'Pasta Gigi Colgate', th: 'ยาสีฟันคอลเกต', zh: 'Colgate牙膏' },
  'ยาสีฟันColgate牙膏1': { en: 'Colgate Toothpaste', vi: 'Kem đánh răng Colgate', id: 'Pasta Gigi Colgate', th: 'ยาสีฟันคอลเกต', zh: 'Colgate牙膏' },
  'ยาสีฟันColgate牙膏2': { en: 'Colgate Toothpaste', vi: 'Kem đánh răng Colgate', id: 'Pasta Gigi Colgate', th: 'ยาสีฟันคอลเกต', zh: 'Colgate牙膏' },
  'ยาสีฟันColgate牙膏3': { en: 'Colgate Toothpaste', vi: 'Kem đánh răng Colgate', id: 'Pasta Gigi Colgate', th: 'ยาสีฟันคอลเกต', zh: 'Colgate牙膏' },
  'ยาสีฟันColgate牙膏5': { en: 'Colgate Toothpaste', vi: 'Kem đánh răng Colgate', id: 'Pasta Gigi Colgate', th: 'ยาสีฟันคอลเกต', zh: 'Colgate牙膏' },
  'ยาสีฟันColgate牙膏4': { en: 'Colgate Toothpaste', vi: 'Kem đánh răng Colgate', id: 'Pasta Gigi Colgate', th: 'ยาสีฟันคอลเกต', zh: 'Colgate牙膏' },
  'โลชั่นบำรุงผิวCOSWAY身體乳': { en: 'Cosway Body Lotion', vi: 'Sữa dưỡng thể Cosway', id: 'Lotion Tubuh Cosway', th: 'โลชั่นบำรุงผิวคอสเวย์', zh: 'COSWAY身體乳' },
  'โลชั่นบำรุงผิวVaseline乳液': { en: 'Vaseline Body Lotion', vi: 'Sữa dưỡng thể Vaseline', id: 'Lotion Tubuh Vaseline', th: 'โลชั่นบำรุงผิววาสลีน', zh: 'Vaseline乳液' },
  'โลชั่นบำรุงผิวVaseline乳液1': { en: 'Vaseline Body Lotion', vi: 'Sữa dưỡng thể Vaseline', id: 'Lotion Tubuh Vaseline', th: 'โลชั่นบำรุงผิววาสลีน', zh: 'Vaseline乳液' },
  'โลชั่นบำรุงผิวVaseline乳液2': { en: 'Vaseline Body Lotion', vi: 'Sữa dưỡng thể Vaseline', id: 'Lotion Tubuh Vaseline', th: 'โลชั่นบำรุงผิววาสลีน', zh: 'Vaseline乳液' },
  'โลชั่นบำรุงผิวVaseline乳液3': { en: 'Vaseline Body Lotion', vi: 'Sữa dưỡng thể Vaseline', id: 'Lotion Tubuh Vaseline', th: 'โลชั่นบำรุงผิววาสลีน', zh: 'Vaseline乳液' },
  'โลชั่นบำรุงผิวVaseline乳液4': { en: 'Vaseline Body Lotion', vi: 'Sữa dưỡng thể Vaseline', id: 'Lotion Tubuh Vaseline', th: 'โลชั่นบำรุงผิววาสลีน', zh: 'Vaseline乳液' },
  'โลชั่นบำรุงผิวMistine身體乳': { en: 'Mistine Body Lotion', vi: 'Sữa dưỡng thể Mistine', id: 'Lotion Tubuh Mistine', th: 'โลชั่นบำรุงผิว มิสทิน', zh: 'Mistine身體乳' },
  'วาสลีนVaseline': { en: 'Vaseline Petroleum Jelly', vi: 'Sáp dưỡng ẩm Vaseline Petroleum Jelly', id: 'Vaseline Petroleum Jelly', th: 'วาสลีน', zh: 'Vaseline' },
  'ผงขัดผิว身體去角質粉': { en: 'Body Scrub Powder', vi: 'Bột tẩy tế bào chết toàn thân', id: 'Bubuk Lulur Badan', th: 'ผงขัดผิว', zh: '身體去角質粉' },
  'ผงขัดผิวยกกล่อง身體去角質粉盒': { en: 'Body Scrub Powder (Box)', vi: 'Hộp bột tẩy tế bào chết toàn thân', id: 'Bubuk Lulur Badan (Box)', th: 'ผงขัดผิวยกกล่อง', zh: '身體去角質粉盒' },
  'ผงขัดหน้า面部去角質粉': { en: 'Facial Scrub Powder', vi: 'Bột tẩy tế bào chết da mặt', id: 'Bubuk Scrub Wajah', th: 'ผงขัดหน้า', zh: '面部去角質粉' },
  'ผงขัดหน้ายกกล่อง面部去角質粉盒': { en: 'Facial Scrub Powder (Box)', vi: 'Hộp bột tẩy tế bào chết da mặt', id: 'Bubuk Scrub Wajah (Box)', th: 'ผงขัดหน้ายกกล่อง', zh: '面部去角質粉盒' },
  'สบู่班尼肥皂': { en: 'Bennet Soap', vi: 'Xà phòng Bennet', id: 'Sabun Bennet', th: 'สบู่เบนเนท', zh: '班尼肥皂' },
  'สบู่班尼肥皂1': { en: 'Bennet Soap', vi: 'Xà phòng Bennet', id: 'Sabun Bennet', th: 'สบู่เบนเนท', zh: '班尼肥皂' },
  'สบู่班尼肥皂2': { en: 'Bennet Soap', vi: 'Xà phòng Bennet', id: 'Sabun Bennet', th: 'สบู่เบนเนท', zh: '班尼肥皂' },
  'สบู่班尼肥皂3': { en: 'Bennet Soap', vi: 'Xà phòng Bennet', id: 'Sabun Bennet', th: 'สบู่เบนเนท', zh: '班尼肥皂' },
  'สบู่I香皂': { en: 'Imperial Leather Soap', vi: 'Xà bông Imperial Leather', id: 'Sabun Imperial Leather', th: 'สบู่ ไอ', zh: 'I香皂' },
  'สบู่I香皂1': { en: 'Imperial Leather Soap', vi: 'Xà bông Imperial Leather', id: 'Sabun Imperial Leather', th: 'สบู่ ไอ', zh: 'I香皂' },
  'สบู่I香皂2': { en: 'Imperial Leather Soap', vi: 'Xà bông Imperial Leather', id: 'Sabun Imperial Leather', th: 'สบู่ ไอ', zh: 'I香皂' },
  'สบู่I香皂3': { en: 'Imperial Leather Soap', vi: 'Xà bông Imperial Leather', id: 'Sabun Imperial Leather', th: 'สบู่ ไอ', zh: 'I香皂' },
  'สบู่I香皂4': { en: 'Imperial Leather Soap', vi: 'Xà bông Imperial Leather', id: 'Sabun Imperial Leather', th: 'สบู่ ไอ', zh: 'I香皂' },
  'สบู่I香皂5': { en: 'Imperial Leather Soap', vi: 'Xà bông Imperial Leather', id: 'Sabun Imperial Leather', th: 'สบู่ ไอ', zh: 'I香皂' },
  'สบู่I香皂6': { en: 'Imperial Leather Soap', vi: 'Xà bông Imperial Leather', id: 'Sabun Imperial Leather', th: 'สบู่ ไอ', zh: 'I香皂' },
  'สบู่I香皂7': { en: 'Imperial Leather Soap', vi: 'Xà bông Imperial Leather', id: 'Sabun Imperial Leather', th: 'สบู่ ไอ', zh: 'I香皂' },
  'สบู่I香皂8': { en: 'Imperial Leather Soap', vi: 'Xà bông Imperial Leather', id: 'Sabun Imperial Leather', th: 'สบู่ ไอ', zh: 'I香皂' },
  'สบู่I香皂9': { en: 'Imperial Leather Soap', vi: 'Xà bông Imperial Leather', id: 'Sabun Imperial Leather', th: 'สบู่ ไอ', zh: 'I香皂' },
  'สบู่I香皂10': { en: 'Imperial Leather Soap', vi: 'Xà bông Imperial Leather', id: 'Sabun Imperial Leather', th: 'สบู่ ไอ', zh: 'I香皂' },
  'สบู่I香皂11': { en: 'Imperial Leather Soap', vi: 'Xà bông Imperial Leather', id: 'Sabun Imperial Leather', th: 'สบู่ ไอ', zh: 'I香皂' },
  'โอโม่แกลลอนOMO洗衣精': { en: 'Omo Liquid Laundry Detergent (Gallon)', vi: 'Nước giặt Omo (Can)', id: 'Deterjen Cair Omo (Galon)', th: 'โอโม่แกลลอน', zh: 'OMO洗衣精' },


  // ─── 冷凍食品 / FROZEN FOOD ─────────────────────────────────────────────
  'ไก่ทั้งตัว全雞': { en: 'Whole Chicken', vi: 'Gà nguyên con', id: 'Ayam Utuh', th: 'ไก่ทั้งตัว', zh: '全雞' },
  'ขาไก่雞腳': { en: 'Chicken Feet', vi: 'Chân gà', id: 'Ceker Ayam', th: 'ขาไก่', zh: '雞腳' },
  'ชุดเนื้อวัว牛肉組合': { en: 'Beef Combo Set', vi: 'Combo thịt bò', id: 'Paket Daging Sapi Set', th: 'ชุดเนื้อวัว', zh: '牛肉組合' },
  'คางปลา魚下巴': { en: 'Fish Chin', vi: 'Cằm cá (Ức cá)', id: 'Dagu Ikan', th: 'คางปลา', zh: '魚下巴' },
  'เครื่องในไก่雞內臟': { en: 'Chicken Offal', vi: 'Lòng gà', id: 'Jeroan Ayam', th: 'เครื่องในไก่', zh: '雞內臟' },
  'เครื่องในวัว牛雜': { en: 'Beef Offal', vi: 'Lòng bò', id: 'Jeroan Sapi', th: 'เครื่องในวัว', zh: '牛雜' },
  'ปลาดุก土虱1': { en: 'Walking Catfish', vi: 'Cá trê', id: 'Ikan Lele', th: 'ปลาดุก', zh: '土虱' },
  'ปลาดุก土虱': { en: 'Walking Catfish', vi: 'Cá trê', id: 'Ikan Lele', th: 'ปลาดุก', zh: '土虱' },
  'ปลาทู鯖魚': { en: 'Short Mackerel', vi: 'Cá bạc má', id: 'Ikan Kembung', th: 'ปลาทู', zh: '鯖魚' },
  'ปลาทู鯖魚1': { en: 'Short Mackerel', vi: 'Cá bạc má', id: 'Ikan Kembung', th: 'ปลาทู', zh: '鯖魚' },
  'ปลาส้ม酸魚片': { en: 'Pla Som', vi: 'Cá chua Thái Lan', id: 'Pla Som', th: 'ปลาส้ม', zh: '酸魚片' },
  'ปีกไก่雞翅': { en: 'Chicken Wings', vi: 'Cánh gà', id: 'Sayap Ayam', th: 'ปีกไก่', zh: '雞翅' },
  'ตีนไก่鳳爪': { en: 'Chicken Feet', vi: 'Chân gà', id: 'Ceker Ayam', th: 'ตีนไก่', zh: '鳳爪' },
  'ลิ้นหมู豬舌': { en: 'Frozen Pork Tongue', vi: 'Lưỡi heo đông lạnh', id: 'Lidah Babi Beku', th: 'ลิ้นหมู', zh: '豬舌' },
  'ลูกชิ้นเนื้อ牛肉丸': { en: 'Frozen Beef Balls', vi: 'Bò viên đông lạnh', id: 'Bakso Sapi Beku', th: 'ลูกชิ้นเนื้อ', zh: '牛肉丸' },
  'ลูกชิ้นปลา魚丸': { en: 'Frozen Fish Balls', vi: 'Cá viên đông lạnh', id: 'Bakso Ikan Beku', th: 'ลูกชิ้นปลา', zh: '魚丸' },
  'ลูกชิ้นปลา魚丸1': { en: 'Frozen Fish Balls', vi: 'Cá viên đông lạnh', id: 'Bakso Ikan Beku', th: 'ลูกชิ้นปลา', zh: '魚丸' },
  'ลูกชิ้นปลา魚丸2': { en: 'Frozen Fish Balls', vi: 'Cá viên đông lạnh', id: 'Bakso Ikan Beku', th: 'ลูกชิ้นปลา', zh: '魚丸' },
  'ลูกชิ้นหมู豬肉丸': { en: 'Frozen Pork Balls', vi: 'Heo viên đông lạnh', id: 'Bakso Babi Beku', th: 'ลูกชิ้นหมู', zh: '豬肉丸' },
  'แหนมหมู大酸肉': { en: 'Thai Fermented Pork Sour Sausage (Naem)', vi: 'Nem chua heo Thái', id: 'Sosis Babi Fermentasi Khas Thai (Naem)', th: 'แหนมหมู', zh: '大酸肉' },
  'แหนมหมูแท่งยาว長酸肉': { en: 'Long Fermented Pork Sausage Stick', vi: 'Nem chua heo thanh dài', id: 'Sosis Babi Fermentasi Panjang', th: 'แหนมหมูแท่งยาว', zh: '長酸肉' },
  'ฮอตดอกใหญ่大熱狗': { en: 'Giant Hot Dog', vi: 'Xúc xích hot dog lớn', id: 'Sosis Hot Dog Besar', th: 'ฮอตดอกใหญ่', zh: '大熱狗' },
  'ผลไม้ดอง醃水果': { en: 'Pickled Fruits', vi: 'Trái cây ngâm chua ngọt', id: 'Manisan Buah', th: 'ผลไม้ดอง', zh: '醃水果' },
  'ผลไม้ดอง醃水果1': { en: 'Pickled Fruits', vi: 'Trái cây ngâm chua ngọt', id: 'Manisan Buah', th: 'ผลไม้ดอง', zh: '醃水果' },
  'กระชาย甲猜': { en: 'Fingerroot (Krachai)', vi: 'Củ ngải bún (Krachai)', id: 'Temu Kunci (Krachai)', th: 'กระชาย', zh: '甲猜' },
  'ปลาหมึกวง魷魚圈': { en: 'Frozen Squid Rings', vi: 'Mực ống cắt khoanh đông lạnh', id: 'Cumi Ring Beku', th: 'ปลาหมึกวง', zh: '魷魚圈' },
  'หน่อไม้醃竹筍': { en: 'Frozen Pickled Bamboo Shoots', vi: 'Măng ngâm đông lạnh', id: 'Rebung Acar Beku', th: 'หน่อไม้', zh: '醃竹筍' },
  'หมูยอ越南火腿': { en: 'Vietnamese Pork Sausage', vi: 'Chả lụa Việt Nam', id: 'Sosis Babi Vietnam', th: 'หมูยอ', zh: '越南火腿' },
  'หมูสด豬肉': { en: 'Frozen Raw Pork', vi: 'Thịt heo tươi đông lạnh', id: 'Daging Babi Mentah Beku', th: 'หมูสด', zh: '豬肉' },


  // ─── 米類 / RICE ──────────────────────────────────────────────────
  'ข้าวเหนียว5กก.糯米5kg': { en: 'Sticky Rice 5kg', vi: 'Gạo nếp 5kg', id: 'Beras Ketan 5kg', th: 'ข้าวเหนียว 5 กก.', zh: '糯米5kg' },
  'ข้าวเหนียว30กก.糯米30kg': { en: 'Sticky Rice 30kg', vi: 'Gạo nếp 30kg', id: 'Beras Ketan 30kg', th: 'ข้าวเหนียว 30 กก.', zh: '糯米30kg' },
  'ข้าวหอมมะลิ5กก.香米5kg': { en: 'Jasmine Rice 5kg', vi: 'Gạo thơm 5kg', id: 'Beras Melati 5kg', th: 'ข้าวหอมมะลิ 5 กก.', zh: '香米5kg' },
  'ข้าวหอมมะลิ12กก.香米12kg': { en: 'Jasmine Rice 12kg', vi: 'Gạo thơm 12kg', id: 'Beras Melati 12kg', th: 'ข้าวหอมมะลิ 12 กก.', zh: '香米12kg' },

  // ─── 其他 / OTHER & OTHERS ─────────────────────────────────────────────
  'คลิป平口夾2': { en: 'Flat Clip', vi: 'Kẹp miệng phẳng', id: 'Klip Datar', th: 'คลิป', zh: '平口夾' },
  'คลิป平口夾1': { en: 'Flat Clip', vi: 'Kẹp miệng phẳng', id: 'Klip Datar', th: 'คลิป', zh: '平口夾' },
  '白色調胃素': { en: 'White Stomach Medicine', vi: 'Thuốc dạ dày màu trắng', id: 'Obat Lambung Putih', th: '白色調胃素', zh: '白色調胃素' },
  '除蟲藥': { en: 'Insecticide', vi: 'Thuốc diệt côn trùng', id: 'Obat Pembasmi Serangga', th: '除蟲藥', zh: '除蟲藥' },
  'ยางรัด橡皮圈1': { en: 'Rubber Bands', vi: 'Dây thun', id: 'Karet Gelang', th: 'ยางรัด', zh: '橡皮圈' },
  'ยางรัด橡皮圈2': { en: 'Rubber Bands', vi: 'Dây thun', id: 'Karet Gelang', th: 'ยางรัด', zh: '橡皮圈' },
  'หวีฟันห่าง關刀梳': { en: 'Wide Tooth Comb', vi: 'Lược răng thưa', id: 'Sisir Gigi Jarang', th: 'หวีฟันห่าง', zh: '關刀梳' },
  'แปรงสีฟันColgate牙刷': { en: 'Colgate Toothbrush', vi: 'Bàn chải đánh răng Colgate', id: 'Sikat Gigi Colgate', th: 'แปรงสีฟัน', zh: 'Colgate牙刷' },
  'Mixed fruit': { en: 'Mixed Fruit', vi: 'Trái cây hỗn hợp', id: 'Buah Campur', th: 'Mixed fruit', zh: 'Mixed fruit' },
  'กาวตราช้าง三秒膠': { en: 'Elephant Super Glue', vi: 'Keo 502 con voi', id: 'Lem Setan Cap Gajah', th: 'กาวตราช้าง', zh: '三秒膠' },
  'แก้วกาแฟ蝴蝶杯': { en: 'Coffee Butterfly Cup', vi: 'Ly cà phê bướm', id: 'Cangkir Kopi Kupu-kupu', th: 'แก้วกาแฟ', zh: '蝴蝶杯' },
  'แก๊สกระป๋อง瓦斯罐一個': { en: 'Butane Gas Canister', vi: 'Bình ga mini', id: 'Tabung Gas Portabel', th: 'แก๊สกระป๋อง', zh: '瓦斯罐一個' },
  'ไฟแช็ก打火機': { en: 'Lighter', vi: 'Bật lửa', id: 'Korek Api Gas', th: 'ไฟแช็ก', zh: '打火機' },
  'ไพ่撲克牌': { en: 'Poker Cards', vi: 'Bài Poker', id: 'Kartu Poker', th: 'ไพ่', zh: '撲克牌' },
  'พาสเตอแก้ปวด痠痛貼布': { en: 'Pain Relief Patch', vi: 'Miếng dán giảm đau', id: 'Koyo Pereda Nyeri', th: 'พลาสเตอร์แก้ปวด', zh: '痠痛貼布' },
  'เบตาดีนBetadine': { en: 'Betadine Antiseptic Solution', vi: 'Dung dịch sát trùng Betadine', id: 'Obat Luka Betadine', th: 'เบตาดีน', zh: 'Betadine' },
  'ยาแก้ไอเสือดาว烏色止咳水': { en: 'Leopard Brand Cough Syrup', vi: 'Siro ho hiệu Báo Đốm', id: 'Sirup Obat Batuk Cap Macan Tutul', th: 'ยาแก้ไอเสือดาว', zh: '烏色止咳水' },
  'ยาคุม避孕藥': { en: 'Contraceptive', vi: 'Thuốc tránh thai', id: 'Pil KB', th: 'ยาคุม', zh: '避孕藥' },
  'ยาดมโป๊ยเซียน八仙薄荷香筒': { en: 'Poy-Sian Inhaler', vi: 'Ống hít mũi Poy-Sian (Bát Tiên)', id: 'Inhaler Poy-Sian', th: 'ยาดมโป๊ยเซียน', zh: '八仙薄荷香筒' },
  'ยาอมแก้ไอStrepsils': { en: 'Strepsils Cough Lozenges', vi: 'Viên ngậm ho Strepsils', id: 'Permen Pelega Tenggorokan Strepsils', th: 'ยาอมแก้ไอสเตร็ปซิล', zh: 'Strepsils' },
  'สเปรย์แก้ไอ巴西綠蜂膠': { en: 'Brazilian Green Propolis Cough Spray', vi: 'Chai xịt ho keo ong xanh Brazil', id: 'Semprotan Batuk Propolis Hijau Brasil', th: 'สเปรย์แก้ไอโปรโพลิส', zh: '巴西綠蜂膠' },
  'หม้อนึ่งข้าวเหนียว鋁蒸籠': { en: 'Aluminum Sticky Rice Steamer Pot', vi: 'Nồi hấp xôi bằng nhôm', id: 'Panci Kukusan Alumunium Beras Ketan', th: 'หม้อนึ่งข้าวเหนียว', zh: '鋁蒸籠' },
  'แอนตาซิล胃藥': { en: 'Antacil Antacid Tablets', vi: 'Thuốc đau dạ dày Antacil', id: 'Obat Sakit Maag Antacil', th: 'แอนตาซิล', zh: '胃藥' },
  'เฮโมวิตHaemoVit': { en: 'HaemoVit Vitamin Tonic', vi: 'Bổ máu HaemoVit', id: 'Suplemen Penambah Darah HaemoVit', th: 'เฮโมวิต', zh: 'HaemoVit' },
  'กระติ๊บข้าวเล็ก竹簍盒小': { en: 'Small Bamboo Sticky Rice Basket (Kratip)', vi: 'Giỏ tre đựng xôi cỡ nhỏ', id: 'Wadah Nasi Ketan Anyaman Bambu Kecil (Kratip)', th: 'กระติ๊บข้าวเล็ก', zh: '竹簍盒小' },
  'กระติ๊บข้าวใหญ่竹簍盒大': { en: 'Large Bamboo Sticky Rice Basket (Kratip)', vi: 'Giỏ tre đựng xôi cỡ lớn', id: 'Wadah Nasi Ketan Anyaman Bambu Besar (Kratip)', th: 'กระติ๊บข้าวใหญ่', zh: '竹簍盒大' },
  'กระโปรงกางเกงหญิง女性褲裙': { en: 'Women Culottes', vi: 'Quần giả váy nữ', id: 'Rok Celana Wanita', th: 'กระโปรงกางเกงหญิง', zh: '女性褲裙' },
  'กางเกงขายาว長褲': { en: 'Trousers', vi: 'Quần dài', id: 'Celana Panjang', th: 'กางเกงขายาว', zh: '長褲' },
  'กางเกงขาสั้น短褲': { en: 'Shorts', vi: 'Quần short', id: 'Celana Pendek', th: 'กางเกงขาสั้น', zh: '短褲' },
  'กางเกงใน內褲': { en: 'Underwear', vi: 'Quần lót', id: 'Celana Dalam', th: 'กางเกงใน', zh: '內褲' },
  'ชุดกีฬาผู้หญิง運動女裝': { en: 'Women Sportswear Set', vi: 'Set đồ thể thao nữ', id: 'Setelan Baju Olahraga Wanita', th: 'ชุดกีฬาผู้หญิง', zh: '運動女裝' },
  'ชุดมีดโกน剃刀盒': { en: 'Razor & Blades Set Box', vi: 'Hộp dao cạo râu', id: 'Kotak Set Alat Cukur Shaver', th: 'ชุดมีดโกน', zh: '剃刀盒' },
  'ตะเกียบ免洗筷': { en: 'Disposable Chopsticks', vi: 'Đũa dùng một lần', id: 'Sumpit Sekali Pakai', th: 'ตะเกียบ', zh: '免洗筷' },
  'ถ้วยไฮโล瓷盤': { en: 'Hi-Lo Gambling Porcelain Plate', vi: 'Đĩa sứ chơi Sicbo / Hi-Lo', id: 'Piring Porselen Dadu Hi-Lo', th: 'ถ้วยไฮโล', zh: '瓷盤' },
  'ถุงเท้า 1 คู่襪子一雙': { en: 'Socks (1 Pair)', vi: 'Vớ / Tất (1 đôi)', id: 'Kaus Kaki (1 Pasang)', th: 'ถุงเท้า 1 คู่', zh: '襪子一雙' },
  'ที่ตัดเล็บ指甲剪': { en: 'Nail Clippers', vi: 'Bấm móng tay', id: 'Gunting Kuku', th: 'ที่ตัดเล็บ', zh: '指甲剪' },
  'แป้นไฮโล賭紙': { en: 'Hi-Lo Gambling Layout Mat / Paper', vi: 'Bạt sơ đồ đặt cược Sicbo / Hi-Lo', id: 'Kertas Papan Taruhan Dadu Hi-Lo', th: 'แป้นไฮโล', zh: '賭紙' },
  'ฝาไฮโล竹帽': { en: 'Hi-Lo Gambling Bamboo Cover Mat', vi: 'Nắp tre đậy đĩa Sicbo / Hi-Lo', id: 'Penutup Anyaman Bambu Dadu Hi-Lo', th: 'ฝาไฮโล', zh: '竹帽' },
  'รองเท้าแตะลายช้าง大象拖鞋': { en: 'Elephant Pattern Slippers', vi: 'Dép tông họa tiết voi Thái Lan', id: 'Sandal Jepit Motif Gajah', th: 'รองเท้าแตะลายช้าง', zh: '大象拖鞋' },
  'ลูกเต๋า 3 ลูก3個骰子': { en: '3 Dices', vi: '3 viên xúc xắc / xí ngầu', id: '3 Buah Dadu', th: 'ลูกเต๋า 3 ลูก', zh: '3個骰子' },
  'ส้อม叉子': { en: 'Fork', vi: 'Nĩa', id: 'Garpu', th: 'ส้อม', zh: '叉子' },
  'เสื่อ地蓆': { en: 'Mat', vi: 'Chiếu trải sàn', id: 'Tikar', th: 'เสื่อ', zh: '地蓆' },
  'เสื้อแขนกุดหญิง無袖女裝': { en: 'Women Sleeveless Shirt', vi: 'Áo ba lỗ', id: 'Baju Tanpa Lengan Wanita', th: 'เสื้อแขนกุดหญิง', zh: '無袖女裝' },
  'หมวก帽子': { en: 'Hat', vi: 'Mũ', id: 'Topi', th: 'หมวก', zh: '帽子' },
  'หม้ออลูมิเนียม鋁鍋': { en: 'Aluminum Pot', vi: 'Nồi nhôm', id: 'Panci Alumunium', th: 'หม้ออลูมิเนียม', zh: '鋁鍋' },
  'หวดนึ่งข้าว竹蒸籠三角': { en: 'Triangular Bamboo Sticky Rice Steaming Basket (Huat)', vi: 'Chõ tre hấp xôi hình nón', id: 'Kukusan Anyaman Bambu Segitiga (Huat)', th: 'หวดนึ่งข้าว', zh: '竹蒸籠三角' },
  'ลิปสติก護唇膏': { en: 'Lip Balm', vi: 'Son dưỡng môi', id: 'Pelembab Bibir', th: 'ลิปสติก', zh: '護唇膏' },
  'ลิปสติก護唇膏1': { en: 'Lip Balm', vi: 'Son dưỡng môi', id: 'Pelembab Bibir', th: 'ลิปสติก', zh: '護唇膏' }


};